DECLARE @INS_COMMON_BINARY_DATA_VALUE_FOR_DELETE TABLE(ID uniqueidentifier)

INSERT INTO @INS_COMMON_BINARY_DATA_VALUE_FOR_DELETE
SELECT  INS_COMMON_BINARY_DATA_VALUE.ID 
FROM INS_COMMON_BINARY_DATA_VALUE
WHERE 
[INS_COMMON_BINARY_DATA_VALUE].[ID] IN ({0})
;


DELETE INS_COMMON_BINARY_DATA_VALUE FROM INS_COMMON_BINARY_DATA_VALUE tab JOIN @INS_COMMON_BINARY_DATA_VALUE_FOR_DELETE idlist ON tab.ID = idlist.ID
