SELECT DISTINCT KSS_CHECK.* 
FROM KSS_CHECK
 JOIN KSS_OPERATION ON KSS_CHECK.ID = KSS_OPERATION.KSS_CHECK_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_POS.* 
FROM KSS_POS
 JOIN KSS_OPERATION ON KSS_POS.ID = KSS_OPERATION.KSS_POS_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_TRANSF_CASH_COPY.* 
FROM KSS_TRANSF_CASH_COPY
 JOIN KSS_OPERATION ON KSS_TRANSF_CASH_COPY.ID = KSS_OPERATION.KSS_TRANSF_CASH_COPY_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_INVOICE_COPY.* 
FROM KSS_INVOICE_COPY
 JOIN KSS_OPERATION ON KSS_INVOICE_COPY.ID = KSS_OPERATION.KSS_INVOICE_COPY_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_CASH.* 
FROM KSS_CASH
WHERE 
[KSS_CASH].[ID] IN ({0})
;

SELECT DISTINCT KSS_CASH_DOCUMENT.* 
FROM KSS_CASH_DOCUMENT
WHERE 
[KSS_CASH_DOCUMENT].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_OPERATION.* 
FROM KSS_OPERATION
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_OPERATION_DOCUMENT.* 
FROM KSS_OPERATION_DOCUMENT
 JOIN KSS_OPERATION ON KSS_OPERATION_DOCUMENT.KSS_OPERATION_ID = KSS_OPERATION.ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

SELECT DISTINCT KSS_OPERATION_ORD_POSITION_RSP.* 
FROM KSS_OPERATION_ORD_POSITION_RSP
 JOIN KSS_OPERATION ON KSS_OPERATION_ORD_POSITION_RSP.KSS_OPERATION_ID = KSS_OPERATION.ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;
