DECLARE @SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @SYS_ESCALATION_LEVEL_FOR_DELETE TABLE(ID int)
DECLARE @SYS_DOCUMENT_TEXT_CONFIGURATION_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_TOP_ORG_UNIT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_ORG_COST_CENTER_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_OPEN_TIME_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_INFO_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_FEDERAL_STATE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_BANK_INFO_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_ADDRESS_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_UNIT_ACCOUNT_TYPE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_ORG_UNIT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_INSPECTION_REPORT_TEXT_CONFIGURATION_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_ORGANIZATIONAL_UNIT_FOR_DELETE TABLE(ID int)
DECLARE @ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORG_COST_CENTER_PRICE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_PROVISION_COST_FOR_DELETE TABLE(ID int)
DECLARE @ORD_EMAIL_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_PRICE_FOR_DELETE TABLE(ID int)
DECLARE @INS_SEVERITY_VALID_PERIOD_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_SEVERITY_NEXT_INSPECTION_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_SEVERITY_LABEL_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_REGION_PRICE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_PRICE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_DISCOUNT_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_LOCALIZATION_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_EXPIRATION_INFO_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_TOP_EMPLOYEE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_SYS_ROLE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_ORG_COST_CENTER_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_INFO_TYPE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_CASH_PERMISSION_FOR_DELETE TABLE(ID int)
DECLARE @SYS_LOCATION_FOR_DELETE TABLE(ID int)
DECLARE @ORD_RECOGNITION_AREA_OF_WORK_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_ADDRESS_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_VALID_PERIOD_PRODUCT_CLASS_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_UNIT_CODE_FOR_DELETE TABLE(ID int)
DECLARE @INS_SPECIFIC_DATA_FOR_DELETE TABLE(ID int)
DECLARE @INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_LABEL_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_FOR_DELETE TABLE(ID int)
DECLARE @EMP_CORE_ADDRESS_RECOGNITION_RSP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_CORE_ADDRESS_FEDERAL_STATE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @SYS_ROLE_SYS_PERMISSION_RSP_FOR_DELETE TABLE(ID int)
DECLARE @SYS_NOTIFICATION_FOR_DELETE TABLE(ID int)
DECLARE @SYS_DEFAULT_LANGUAGE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_RECOGNITION_FOR_DELETE TABLE(ID int)
DECLARE @ORD_FEDERAL_STATE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_TAX_INFO_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_PARTNER_ROLE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_LOCK_INFO_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_INFO_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_BILLING_PARAMETER_RSP_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CONTACT_PERSON_FOR_DELETE TABLE(ID int)
DECLARE @KSS_EXPENSE_GROUND_FOR_DELETE TABLE(ID int)
DECLARE @INS_TEMPLATE_FOR_DELETE TABLE(ID int)
DECLARE @INS_TAX_INFO_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_COMBINATION_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_CLASS_FOR_DELETE TABLE(ID int)
DECLARE @INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP_FOR_DELETE TABLE(ID int)
DECLARE @INS_MEASURABLE_VALUE_FOR_DELETE TABLE(ID int)
DECLARE @INS_AVAILABLE_INSPECTION_TEXT_VALUE_FOR_DELETE TABLE(ID int)
DECLARE @INS_AVAILABLE_INSPECTION_STEP_FOR_DELETE TABLE(ID int)
DECLARE @EMP_CORE_ADDRESS_FOR_DELETE TABLE(ID int)
DECLARE @VHL_SPECIAL_INFO_FOR_DELETE TABLE(ID int)
DECLARE @VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP_FOR_DELETE TABLE(ID int)
DECLARE @VHL_COLOR_FOR_DELETE TABLE(ID int)
DECLARE @SYS_ROLE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_POST_CODE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_POS_CONFIGURATION_FOR_DELETE TABLE(ID int)
DECLARE @SYS_PERMISSION_FOR_DELETE TABLE(ID int)
DECLARE @SYS_PAPER_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_NOTIFICATION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_MODULE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_LANGUAGE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_INFO_KEY_FOR_DELETE TABLE(ID int)
DECLARE @SYS_ENCRYPTION_METADATA_FOR_DELETE TABLE(ID int)
DECLARE @SYS_EMERGENCY_KEY_FOR_DELETE TABLE(ID int)
DECLARE @SYS_DOCUMENT_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @SYS_CURRENCY_FOR_DELETE TABLE(ID int)
DECLARE @SYS_COUNTRY_FOR_DELETE TABLE(ID int)
DECLARE @SYS_CONFIGURATION_FOR_DELETE TABLE(ID int)
DECLARE @SYS_ACTION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORG_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORG_OPEN_TIME_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORG_INSPECTION_DEVICE_FOR_DELETE TABLE(ID int)
DECLARE @ORG_INFORMATION_FOR_DELETE TABLE(ID int)
DECLARE @ORG_COST_CENTER_FOR_DELETE TABLE(ID int)
DECLARE @ORG_BANK_INFORMATION_FOR_DELETE TABLE(ID int)
DECLARE @ORG_ACCOUNTING_AREA_FOR_DELETE TABLE(ID int)
DECLARE @ORG_ACCOUNT_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_SAP_STATUS_FOR_DELETE TABLE(ID int)
DECLARE @ORD_RECOGNITION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_PRODUCT_STATUS_FOR_DELETE TABLE(ID int)
DECLARE @ORD_PARTNER_ROLE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_ORDER_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_ORDER_STATUS_FOR_DELETE TABLE(ID int)
DECLARE @ORD_ORDER_CANCELATION_REASON_FOR_DELETE TABLE(ID int)
DECLARE @ORD_ORDER_ADDITIONAL_INFORMATION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_ESCALATION_LEVEL_ACTION_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_INFO_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CUSTOMER_FOR_DELETE TABLE(ID int)
DECLARE @ORD_CONTACT_PERSON_FUNCTION_FOR_DELETE TABLE(ID int)
DECLARE @ORD_BILLING_PARAMETER_FOR_DELETE TABLE(ID int)
DECLARE @ORD_BILL_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @ORD_AREA_OF_WORK_FOR_DELETE TABLE(ID int)
DECLARE @ORD_ADDITIONAL_PAYMENTS_FOR_DELETE TABLE(ID int)
DECLARE @KSS_PAYMENT_METHOD_FOR_DELETE TABLE(ID int)
DECLARE @KSS_OPERATION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @KSS_OPERATION_STATUS_FOR_DELETE TABLE(ID int)
DECLARE @KSS_DOCUMENT_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @KSS_CASH_STATUS_FOR_DELETE TABLE(ID int)
DECLARE @INS_VAT_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_VALID_PERIOD_FOR_DELETE TABLE(ID int)
DECLARE @INS_TAX_CODE_FOR_DELETE TABLE(ID int)
DECLARE @INS_TAX_CLASS_FOR_DELETE TABLE(ID int)
DECLARE @INS_SUMMARY_FIELD_FOR_DELETE TABLE(ID int)
DECLARE @INS_SEVERITY_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_OBJECT_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_OBJECT_CLASS_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_MATERIAL_GROUP_FOR_DELETE TABLE(ID int)
DECLARE @INS_PRODUCT_COMBINATION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PFP_VEHICLE_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_PFP_POSITION_FOR_DELETE TABLE(ID int)
DECLARE @INS_PFP_INSPECTION_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_OPTICAL_DEFECT_FOR_DELETE TABLE(ID int)
DECLARE @INS_NOT_MEASURABLE_VALUE_FOR_DELETE TABLE(ID int)
DECLARE @INS_NEXT_SP_INTERVAL_FOR_DELETE TABLE(ID int)
DECLARE @INS_NEXT_INSPECTION_FOR_DELETE TABLE(ID int)
DECLARE @INS_META_DATA_FOR_DELETE TABLE(ID int)
DECLARE @INS_MEASURE_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_INSPECTION_STEP_FOR_DELETE TABLE(ID int)
DECLARE @INS_INSPECTION_REPORT_STATUS_FOR_DELETE TABLE(ID int)
DECLARE @INS_EG_DOK_SERVICE_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @INS_CORE_DATA_PRODUCT_GROUP_FOR_DELETE TABLE(ID int)
DECLARE @INS_BRAKE_INSPECTION_METHOD_FOR_DELETE TABLE(ID int)
DECLARE @INS_AVAILABLE_INSPECTION_TEXT_FOR_DELETE TABLE(ID int)
DECLARE @EXP_TRIP_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @EXP_PASSENGERS_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @EMP_EMPLOYEE_INFO_TYPE_FOR_DELETE TABLE(ID int)
DECLARE @EMP_CORE_ADDRESS_TYPE_FOR_DELETE TABLE(ID int)

INSERT INTO @SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP_FOR_DELETE
SELECT  SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP.ID 
FROM SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP
WHERE 
[SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_ESCALATION_LEVEL_FOR_DELETE
SELECT  SYS_ESCALATION_LEVEL.ID 
FROM SYS_ESCALATION_LEVEL
WHERE 
[SYS_ESCALATION_LEVEL].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_DOCUMENT_TEXT_CONFIGURATION_FOR_DELETE
SELECT  SYS_DOCUMENT_TEXT_CONFIGURATION.ID 
FROM SYS_DOCUMENT_TEXT_CONFIGURATION
WHERE 
[SYS_DOCUMENT_TEXT_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_TOP_ORG_UNIT_RSP_FOR_DELETE
SELECT  ORG_UNIT_TOP_ORG_UNIT_RSP.ID 
FROM ORG_UNIT_TOP_ORG_UNIT_RSP
WHERE 
[ORG_UNIT_TOP_ORG_UNIT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_ORG_COST_CENTER_RSP_FOR_DELETE
SELECT  ORG_UNIT_ORG_COST_CENTER_RSP.ID 
FROM ORG_UNIT_ORG_COST_CENTER_RSP
WHERE 
[ORG_UNIT_ORG_COST_CENTER_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_OPEN_TIME_RSP_FOR_DELETE
SELECT  ORG_UNIT_OPEN_TIME_RSP.ID 
FROM ORG_UNIT_OPEN_TIME_RSP
WHERE 
[ORG_UNIT_OPEN_TIME_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_INFO_RSP_FOR_DELETE
SELECT  ORG_UNIT_INFO_RSP.ID 
FROM ORG_UNIT_INFO_RSP
WHERE 
[ORG_UNIT_INFO_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_FEDERAL_STATE_RSP_FOR_DELETE
SELECT  ORG_UNIT_FEDERAL_STATE_RSP.ID 
FROM ORG_UNIT_FEDERAL_STATE_RSP
WHERE 
[ORG_UNIT_FEDERAL_STATE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_BANK_INFO_RSP_FOR_DELETE
SELECT  ORG_UNIT_BANK_INFO_RSP.ID 
FROM ORG_UNIT_BANK_INFO_RSP
WHERE 
[ORG_UNIT_BANK_INFO_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_ADDRESS_RSP_FOR_DELETE
SELECT  ORG_UNIT_ADDRESS_RSP.ID 
FROM ORG_UNIT_ADDRESS_RSP
WHERE 
[ORG_UNIT_ADDRESS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_UNIT_ACCOUNT_TYPE_RSP_FOR_DELETE
SELECT  ORG_UNIT_ACCOUNT_TYPE_RSP.ID 
FROM ORG_UNIT_ACCOUNT_TYPE_RSP
WHERE 
[ORG_UNIT_ACCOUNT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_ORG_UNIT_RSP_FOR_DELETE
SELECT  ORD_CUSTOMER_ORG_UNIT_RSP.ID 
FROM ORD_CUSTOMER_ORG_UNIT_RSP
WHERE 
[ORD_CUSTOMER_ORG_UNIT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_INSPECTION_REPORT_TEXT_CONFIGURATION_FOR_DELETE
SELECT  INS_INSPECTION_REPORT_TEXT_CONFIGURATION.ID 
FROM INS_INSPECTION_REPORT_TEXT_CONFIGURATION
WHERE 
[INS_INSPECTION_REPORT_TEXT_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP_FOR_DELETE
SELECT  EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP.ID 
FROM EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP
WHERE 
[EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP_FOR_DELETE
SELECT  EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP.ID 
FROM EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP
WHERE 
[EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_ORGANIZATIONAL_UNIT_FOR_DELETE
SELECT  ORG_ORGANIZATIONAL_UNIT.ID 
FROM ORG_ORGANIZATIONAL_UNIT
WHERE 
[ORG_ORGANIZATIONAL_UNIT].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP_FOR_DELETE
SELECT  ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP.ID 
FROM ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP
WHERE 
[ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_COST_CENTER_PRICE_FOR_DELETE
SELECT  ORG_COST_CENTER_PRICE.ID 
FROM ORG_COST_CENTER_PRICE
WHERE 
[ORG_COST_CENTER_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_PROVISION_COST_FOR_DELETE
SELECT  ORD_PROVISION_COST.ID 
FROM ORD_PROVISION_COST
WHERE 
[ORD_PROVISION_COST].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_EMAIL_FOR_DELETE
SELECT  ORD_EMAIL.ID 
FROM ORD_EMAIL
WHERE 
[ORD_EMAIL].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_PRICE_FOR_DELETE
SELECT  ORD_CUSTOMER_PRICE.ID 
FROM ORD_CUSTOMER_PRICE
WHERE 
[ORD_CUSTOMER_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SEVERITY_VALID_PERIOD_RSP_FOR_DELETE
SELECT  INS_SEVERITY_VALID_PERIOD_RSP.ID 
FROM INS_SEVERITY_VALID_PERIOD_RSP
WHERE 
[INS_SEVERITY_VALID_PERIOD_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SEVERITY_NEXT_INSPECTION_RSP_FOR_DELETE
SELECT  INS_SEVERITY_NEXT_INSPECTION_RSP.ID 
FROM INS_SEVERITY_NEXT_INSPECTION_RSP
WHERE 
[INS_SEVERITY_NEXT_INSPECTION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SEVERITY_LABEL_RSP_FOR_DELETE
SELECT  INS_SEVERITY_LABEL_RSP.ID 
FROM INS_SEVERITY_LABEL_RSP
WHERE 
[INS_SEVERITY_LABEL_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_REGION_PRICE_FOR_DELETE
SELECT  INS_PRODUCT_REGION_PRICE.ID 
FROM INS_PRODUCT_REGION_PRICE
WHERE 
[INS_PRODUCT_REGION_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_PRICE_FOR_DELETE
SELECT  INS_PRODUCT_PRICE.ID 
FROM INS_PRODUCT_PRICE
WHERE 
[INS_PRODUCT_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_DISCOUNT_FOR_DELETE
SELECT  INS_PRODUCT_DISCOUNT.ID 
FROM INS_PRODUCT_DISCOUNT
WHERE 
[INS_PRODUCT_DISCOUNT].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP_FOR_DELETE
SELECT  INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP.ID 
FROM INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP
WHERE 
[INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP.ID 
FROM INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP.ID 
FROM INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP.ID 
FROM INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_LOCALIZATION_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_LOCALIZATION.ID 
FROM INS_CORE_DATA_PRODUCT_LOCALIZATION
WHERE 
[INS_CORE_DATA_PRODUCT_LOCALIZATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO.ID 
FROM INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO
WHERE 
[INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_EXPIRATION_INFO_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_EXPIRATION_INFO.ID 
FROM INS_CORE_DATA_PRODUCT_EXPIRATION_INFO
WHERE 
[INS_CORE_DATA_PRODUCT_EXPIRATION_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP.ID 
FROM INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_TOP_EMPLOYEE_RSP_FOR_DELETE
SELECT  EMP_EMPLOYEE_TOP_EMPLOYEE_RSP.ID 
FROM EMP_EMPLOYEE_TOP_EMPLOYEE_RSP
WHERE 
[EMP_EMPLOYEE_TOP_EMPLOYEE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_SYS_ROLE_RSP_FOR_DELETE
SELECT  EMP_EMPLOYEE_SYS_ROLE_RSP.ID 
FROM EMP_EMPLOYEE_SYS_ROLE_RSP
WHERE 
[EMP_EMPLOYEE_SYS_ROLE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_ORG_COST_CENTER_RSP_FOR_DELETE
SELECT  EMP_EMPLOYEE_ORG_COST_CENTER_RSP.ID 
FROM EMP_EMPLOYEE_ORG_COST_CENTER_RSP
WHERE 
[EMP_EMPLOYEE_ORG_COST_CENTER_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_INFO_TYPE_RSP_FOR_DELETE
SELECT  EMP_EMPLOYEE_INFO_TYPE_RSP.ID 
FROM EMP_EMPLOYEE_INFO_TYPE_RSP
WHERE 
[EMP_EMPLOYEE_INFO_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_CASH_PERMISSION_FOR_DELETE
SELECT  EMP_CASH_PERMISSION.ID 
FROM EMP_CASH_PERMISSION
WHERE 
[EMP_CASH_PERMISSION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_LOCATION_FOR_DELETE
SELECT  SYS_LOCATION.ID 
FROM SYS_LOCATION
WHERE 
[SYS_LOCATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_RECOGNITION_AREA_OF_WORK_RSP_FOR_DELETE
SELECT  ORD_RECOGNITION_AREA_OF_WORK_RSP.ID 
FROM ORD_RECOGNITION_AREA_OF_WORK_RSP
WHERE 
[ORD_RECOGNITION_AREA_OF_WORK_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_ADDRESS_RSP_FOR_DELETE
SELECT  ORD_CUSTOMER_ADDRESS_RSP.ID 
FROM ORD_CUSTOMER_ADDRESS_RSP
WHERE 
[ORD_CUSTOMER_ADDRESS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_VALID_PERIOD_PRODUCT_CLASS_RSP_FOR_DELETE
SELECT  INS_VALID_PERIOD_PRODUCT_CLASS_RSP.ID 
FROM INS_VALID_PERIOD_PRODUCT_CLASS_RSP
WHERE 
[INS_VALID_PERIOD_PRODUCT_CLASS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_UNIT_CODE_FOR_DELETE
SELECT  INS_UNIT_CODE.ID 
FROM INS_UNIT_CODE
WHERE 
[INS_UNIT_CODE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SPECIFIC_DATA_FOR_DELETE
SELECT  INS_SPECIFIC_DATA.ID 
FROM INS_SPECIFIC_DATA
WHERE 
[INS_SPECIFIC_DATA].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP_FOR_DELETE
SELECT  INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP.ID 
FROM INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP
WHERE 
[INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP_FOR_DELETE
SELECT  INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP.ID 
FROM INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP
WHERE 
[INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP_FOR_DELETE
SELECT  INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP.ID 
FROM INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP
WHERE 
[INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_LABEL_RSP_FOR_DELETE
SELECT  INS_PRODUCT_CLASS_LABEL_RSP.ID 
FROM INS_PRODUCT_CLASS_LABEL_RSP
WHERE 
[INS_PRODUCT_CLASS_LABEL_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP_FOR_DELETE
SELECT  INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP.ID 
FROM INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP
WHERE 
[INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION_FOR_DELETE
SELECT  INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION.ID 
FROM INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION
WHERE 
[INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP_FOR_DELETE
SELECT  INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP.ID 
FROM INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP
WHERE 
[INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP_FOR_DELETE
SELECT  INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP.ID 
FROM INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP
WHERE 
[INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT.ID 
FROM INS_CORE_DATA_PRODUCT
WHERE 
[INS_CORE_DATA_PRODUCT].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_FOR_DELETE
SELECT  EMP_EMPLOYEE.ID 
FROM EMP_EMPLOYEE
WHERE 
[EMP_EMPLOYEE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_CORE_ADDRESS_RECOGNITION_RSP_FOR_DELETE
SELECT  EMP_CORE_ADDRESS_RECOGNITION_RSP.ID 
FROM EMP_CORE_ADDRESS_RECOGNITION_RSP
WHERE 
[EMP_CORE_ADDRESS_RECOGNITION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_CORE_ADDRESS_FEDERAL_STATE_RSP_FOR_DELETE
SELECT  EMP_CORE_ADDRESS_FEDERAL_STATE_RSP.ID 
FROM EMP_CORE_ADDRESS_FEDERAL_STATE_RSP
WHERE 
[EMP_CORE_ADDRESS_FEDERAL_STATE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP_FOR_DELETE
SELECT  VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP.ID 
FROM VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP
WHERE 
[VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_ROLE_SYS_PERMISSION_RSP_FOR_DELETE
SELECT  SYS_ROLE_SYS_PERMISSION_RSP.ID 
FROM SYS_ROLE_SYS_PERMISSION_RSP
WHERE 
[SYS_ROLE_SYS_PERMISSION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_NOTIFICATION_FOR_DELETE
SELECT  SYS_NOTIFICATION.ID 
FROM SYS_NOTIFICATION
WHERE 
[SYS_NOTIFICATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_DEFAULT_LANGUAGE_FOR_DELETE
SELECT  SYS_DEFAULT_LANGUAGE.ID 
FROM SYS_DEFAULT_LANGUAGE
WHERE 
[SYS_DEFAULT_LANGUAGE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_RECOGNITION_FOR_DELETE
SELECT  ORD_RECOGNITION.ID 
FROM ORD_RECOGNITION
WHERE 
[ORD_RECOGNITION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_FEDERAL_STATE_FOR_DELETE
SELECT  ORD_FEDERAL_STATE.ID 
FROM ORD_FEDERAL_STATE
WHERE 
[ORD_FEDERAL_STATE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_TAX_INFO_FOR_DELETE
SELECT  ORD_CUSTOMER_TAX_INFO.ID 
FROM ORD_CUSTOMER_TAX_INFO
WHERE 
[ORD_CUSTOMER_TAX_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_PARTNER_ROLE_RSP_FOR_DELETE
SELECT  ORD_CUSTOMER_PARTNER_ROLE_RSP.ID 
FROM ORD_CUSTOMER_PARTNER_ROLE_RSP
WHERE 
[ORD_CUSTOMER_PARTNER_ROLE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP_FOR_DELETE
SELECT  ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP.ID 
FROM ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP
WHERE 
[ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_LOCK_INFO_FOR_DELETE
SELECT  ORD_CUSTOMER_LOCK_INFO.ID 
FROM ORD_CUSTOMER_LOCK_INFO
WHERE 
[ORD_CUSTOMER_LOCK_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_INFO_RSP_FOR_DELETE
SELECT  ORD_CUSTOMER_INFO_RSP.ID 
FROM ORD_CUSTOMER_INFO_RSP
WHERE 
[ORD_CUSTOMER_INFO_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_BILLING_PARAMETER_RSP_FOR_DELETE
SELECT  ORD_CUSTOMER_BILLING_PARAMETER_RSP.ID 
FROM ORD_CUSTOMER_BILLING_PARAMETER_RSP
WHERE 
[ORD_CUSTOMER_BILLING_PARAMETER_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CONTACT_PERSON_FOR_DELETE
SELECT  ORD_CONTACT_PERSON.ID 
FROM ORD_CONTACT_PERSON
WHERE 
[ORD_CONTACT_PERSON].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @KSS_EXPENSE_GROUND_FOR_DELETE
SELECT  KSS_EXPENSE_GROUND.ID 
FROM KSS_EXPENSE_GROUND
WHERE 
[KSS_EXPENSE_GROUND].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_TEMPLATE_FOR_DELETE
SELECT  INS_TEMPLATE.ID 
FROM INS_TEMPLATE
WHERE 
[INS_TEMPLATE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_TAX_INFO_FOR_DELETE
SELECT  INS_TAX_INFO.ID 
FROM INS_TAX_INFO
WHERE 
[INS_TAX_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_COMBINATION_FOR_DELETE
SELECT  INS_PRODUCT_COMBINATION.ID 
FROM INS_PRODUCT_COMBINATION
WHERE 
[INS_PRODUCT_COMBINATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_CLASS_FOR_DELETE
SELECT  INS_PRODUCT_CLASS.ID 
FROM INS_PRODUCT_CLASS
WHERE 
[INS_PRODUCT_CLASS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP_FOR_DELETE
SELECT  INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP.ID 
FROM INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP
WHERE 
[INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_MEASURABLE_VALUE_FOR_DELETE
SELECT  INS_MEASURABLE_VALUE.ID 
FROM INS_MEASURABLE_VALUE
WHERE 
[INS_MEASURABLE_VALUE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_AVAILABLE_INSPECTION_TEXT_VALUE_FOR_DELETE
SELECT  INS_AVAILABLE_INSPECTION_TEXT_VALUE.ID 
FROM INS_AVAILABLE_INSPECTION_TEXT_VALUE
WHERE 
[INS_AVAILABLE_INSPECTION_TEXT_VALUE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_AVAILABLE_INSPECTION_STEP_FOR_DELETE
SELECT  INS_AVAILABLE_INSPECTION_STEP.ID 
FROM INS_AVAILABLE_INSPECTION_STEP
WHERE 
[INS_AVAILABLE_INSPECTION_STEP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_CORE_ADDRESS_FOR_DELETE
SELECT  EMP_CORE_ADDRESS.ID 
FROM EMP_CORE_ADDRESS
WHERE 
[EMP_CORE_ADDRESS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @VHL_SPECIAL_INFO_FOR_DELETE
SELECT  VHL_SPECIAL_INFO.ID 
FROM VHL_SPECIAL_INFO
WHERE 
[VHL_SPECIAL_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP_FOR_DELETE
SELECT  VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP.ID 
FROM VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP
WHERE 
[VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @VHL_COLOR_FOR_DELETE
SELECT  VHL_COLOR.ID 
FROM VHL_COLOR
WHERE 
[VHL_COLOR].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_ROLE_FOR_DELETE
SELECT  SYS_ROLE.ID 
FROM SYS_ROLE
WHERE 
[SYS_ROLE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_POST_CODE_FOR_DELETE
SELECT  SYS_POST_CODE.ID 
FROM SYS_POST_CODE
WHERE 
[SYS_POST_CODE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_POS_CONFIGURATION_FOR_DELETE
SELECT  SYS_POS_CONFIGURATION.ID 
FROM SYS_POS_CONFIGURATION
WHERE 
[SYS_POS_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_PERMISSION_FOR_DELETE
SELECT  SYS_PERMISSION.ID 
FROM SYS_PERMISSION
WHERE 
[SYS_PERMISSION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_PAPER_TYPE_FOR_DELETE
SELECT  SYS_PAPER_TYPE.ID 
FROM SYS_PAPER_TYPE
WHERE 
[SYS_PAPER_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_NOTIFICATION_TYPE_FOR_DELETE
SELECT  SYS_NOTIFICATION_TYPE.ID 
FROM SYS_NOTIFICATION_TYPE
WHERE 
[SYS_NOTIFICATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_MODULE_FOR_DELETE
SELECT  SYS_MODULE.ID 
FROM SYS_MODULE
WHERE 
[SYS_MODULE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_LANGUAGE_FOR_DELETE
SELECT  SYS_LANGUAGE.ID 
FROM SYS_LANGUAGE
WHERE 
[SYS_LANGUAGE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_INFO_KEY_FOR_DELETE
SELECT  SYS_INFO_KEY.ID 
FROM SYS_INFO_KEY
WHERE 
[SYS_INFO_KEY].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_ENCRYPTION_METADATA_FOR_DELETE
SELECT  SYS_ENCRYPTION_METADATA.ID 
FROM SYS_ENCRYPTION_METADATA
WHERE 
[SYS_ENCRYPTION_METADATA].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_EMERGENCY_KEY_FOR_DELETE
SELECT  SYS_EMERGENCY_KEY.ID 
FROM SYS_EMERGENCY_KEY
WHERE 
[SYS_EMERGENCY_KEY].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_DOCUMENT_TYPE_FOR_DELETE
SELECT  SYS_DOCUMENT_TYPE.ID 
FROM SYS_DOCUMENT_TYPE
WHERE 
[SYS_DOCUMENT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_CURRENCY_FOR_DELETE
SELECT  SYS_CURRENCY.ID 
FROM SYS_CURRENCY
WHERE 
[SYS_CURRENCY].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_COUNTRY_FOR_DELETE
SELECT  SYS_COUNTRY.ID 
FROM SYS_COUNTRY
WHERE 
[SYS_COUNTRY].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_CONFIGURATION_FOR_DELETE
SELECT  SYS_CONFIGURATION.ID 
FROM SYS_CONFIGURATION
WHERE 
[SYS_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @SYS_ACTION_TYPE_FOR_DELETE
SELECT  SYS_ACTION_TYPE.ID 
FROM SYS_ACTION_TYPE
WHERE 
[SYS_ACTION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_TYPE_FOR_DELETE
SELECT  ORG_TYPE.ID 
FROM ORG_TYPE
WHERE 
[ORG_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_OPEN_TIME_TYPE_FOR_DELETE
SELECT  ORG_OPEN_TIME_TYPE.ID 
FROM ORG_OPEN_TIME_TYPE
WHERE 
[ORG_OPEN_TIME_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_INSPECTION_DEVICE_FOR_DELETE
SELECT  ORG_INSPECTION_DEVICE.ID 
FROM ORG_INSPECTION_DEVICE
WHERE 
[ORG_INSPECTION_DEVICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_INFORMATION_FOR_DELETE
SELECT  ORG_INFORMATION.ID 
FROM ORG_INFORMATION
WHERE 
[ORG_INFORMATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_COST_CENTER_FOR_DELETE
SELECT  ORG_COST_CENTER.ID 
FROM ORG_COST_CENTER
WHERE 
[ORG_COST_CENTER].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_BANK_INFORMATION_FOR_DELETE
SELECT  ORG_BANK_INFORMATION.ID 
FROM ORG_BANK_INFORMATION
WHERE 
[ORG_BANK_INFORMATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_ACCOUNTING_AREA_FOR_DELETE
SELECT  ORG_ACCOUNTING_AREA.ID 
FROM ORG_ACCOUNTING_AREA
WHERE 
[ORG_ACCOUNTING_AREA].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORG_ACCOUNT_TYPE_FOR_DELETE
SELECT  ORG_ACCOUNT_TYPE.ID 
FROM ORG_ACCOUNT_TYPE
WHERE 
[ORG_ACCOUNT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_SAP_STATUS_FOR_DELETE
SELECT  ORD_SAP_STATUS.ID 
FROM ORD_SAP_STATUS
WHERE 
[ORD_SAP_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_RECOGNITION_TYPE_FOR_DELETE
SELECT  ORD_RECOGNITION_TYPE.ID 
FROM ORD_RECOGNITION_TYPE
WHERE 
[ORD_RECOGNITION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_PRODUCT_STATUS_FOR_DELETE
SELECT  ORD_PRODUCT_STATUS.ID 
FROM ORD_PRODUCT_STATUS
WHERE 
[ORD_PRODUCT_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_PARTNER_ROLE_FOR_DELETE
SELECT  ORD_PARTNER_ROLE.ID 
FROM ORD_PARTNER_ROLE
WHERE 
[ORD_PARTNER_ROLE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_ORDER_TYPE_FOR_DELETE
SELECT  ORD_ORDER_TYPE.ID 
FROM ORD_ORDER_TYPE
WHERE 
[ORD_ORDER_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_ORDER_STATUS_FOR_DELETE
SELECT  ORD_ORDER_STATUS.ID 
FROM ORD_ORDER_STATUS
WHERE 
[ORD_ORDER_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_ORDER_CANCELATION_REASON_FOR_DELETE
SELECT  ORD_ORDER_CANCELATION_REASON.ID 
FROM ORD_ORDER_CANCELATION_REASON
WHERE 
[ORD_ORDER_CANCELATION_REASON].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_ORDER_ADDITIONAL_INFORMATION_TYPE_FOR_DELETE
SELECT  ORD_ORDER_ADDITIONAL_INFORMATION_TYPE.ID 
FROM ORD_ORDER_ADDITIONAL_INFORMATION_TYPE
WHERE 
[ORD_ORDER_ADDITIONAL_INFORMATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_ESCALATION_LEVEL_ACTION_FOR_DELETE
SELECT  ORD_ESCALATION_LEVEL_ACTION.ID 
FROM ORD_ESCALATION_LEVEL_ACTION
WHERE 
[ORD_ESCALATION_LEVEL_ACTION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_INFO_FOR_DELETE
SELECT  ORD_CUSTOMER_INFO.ID 
FROM ORD_CUSTOMER_INFO
WHERE 
[ORD_CUSTOMER_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CUSTOMER_FOR_DELETE
SELECT  ORD_CUSTOMER.ID 
FROM ORD_CUSTOMER
WHERE 
[ORD_CUSTOMER].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_CONTACT_PERSON_FUNCTION_FOR_DELETE
SELECT  ORD_CONTACT_PERSON_FUNCTION.ID 
FROM ORD_CONTACT_PERSON_FUNCTION
WHERE 
[ORD_CONTACT_PERSON_FUNCTION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_BILLING_PARAMETER_FOR_DELETE
SELECT  ORD_BILLING_PARAMETER.ID 
FROM ORD_BILLING_PARAMETER
WHERE 
[ORD_BILLING_PARAMETER].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_BILL_TYPE_FOR_DELETE
SELECT  ORD_BILL_TYPE.ID 
FROM ORD_BILL_TYPE
WHERE 
[ORD_BILL_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_AREA_OF_WORK_FOR_DELETE
SELECT  ORD_AREA_OF_WORK.ID 
FROM ORD_AREA_OF_WORK
WHERE 
[ORD_AREA_OF_WORK].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @ORD_ADDITIONAL_PAYMENTS_FOR_DELETE
SELECT  ORD_ADDITIONAL_PAYMENTS.ID 
FROM ORD_ADDITIONAL_PAYMENTS
WHERE 
[ORD_ADDITIONAL_PAYMENTS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @KSS_PAYMENT_METHOD_FOR_DELETE
SELECT  KSS_PAYMENT_METHOD.ID 
FROM KSS_PAYMENT_METHOD
WHERE 
[KSS_PAYMENT_METHOD].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @KSS_OPERATION_TYPE_FOR_DELETE
SELECT  KSS_OPERATION_TYPE.ID 
FROM KSS_OPERATION_TYPE
WHERE 
[KSS_OPERATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @KSS_OPERATION_STATUS_FOR_DELETE
SELECT  KSS_OPERATION_STATUS.ID 
FROM KSS_OPERATION_STATUS
WHERE 
[KSS_OPERATION_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @KSS_DOCUMENT_TYPE_FOR_DELETE
SELECT  KSS_DOCUMENT_TYPE.ID 
FROM KSS_DOCUMENT_TYPE
WHERE 
[KSS_DOCUMENT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @KSS_CASH_STATUS_FOR_DELETE
SELECT  KSS_CASH_STATUS.ID 
FROM KSS_CASH_STATUS
WHERE 
[KSS_CASH_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_VAT_TYPE_FOR_DELETE
SELECT  INS_VAT_TYPE.ID 
FROM INS_VAT_TYPE
WHERE 
[INS_VAT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_VALID_PERIOD_FOR_DELETE
SELECT  INS_VALID_PERIOD.ID 
FROM INS_VALID_PERIOD
WHERE 
[INS_VALID_PERIOD].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_TAX_CODE_FOR_DELETE
SELECT  INS_TAX_CODE.ID 
FROM INS_TAX_CODE
WHERE 
[INS_TAX_CODE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_TAX_CLASS_FOR_DELETE
SELECT  INS_TAX_CLASS.ID 
FROM INS_TAX_CLASS
WHERE 
[INS_TAX_CLASS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SUMMARY_FIELD_FOR_DELETE
SELECT  INS_SUMMARY_FIELD.ID 
FROM INS_SUMMARY_FIELD
WHERE 
[INS_SUMMARY_FIELD].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_SEVERITY_TYPE_FOR_DELETE
SELECT  INS_SEVERITY_TYPE.ID 
FROM INS_SEVERITY_TYPE
WHERE 
[INS_SEVERITY_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_TYPE_FOR_DELETE
SELECT  INS_PRODUCT_TYPE.ID 
FROM INS_PRODUCT_TYPE
WHERE 
[INS_PRODUCT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_OBJECT_TYPE_FOR_DELETE
SELECT  INS_PRODUCT_OBJECT_TYPE.ID 
FROM INS_PRODUCT_OBJECT_TYPE
WHERE 
[INS_PRODUCT_OBJECT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_OBJECT_CLASS_FOR_DELETE
SELECT  INS_PRODUCT_OBJECT_CLASS.ID 
FROM INS_PRODUCT_OBJECT_CLASS
WHERE 
[INS_PRODUCT_OBJECT_CLASS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_MATERIAL_GROUP_FOR_DELETE
SELECT  INS_PRODUCT_MATERIAL_GROUP.ID 
FROM INS_PRODUCT_MATERIAL_GROUP
WHERE 
[INS_PRODUCT_MATERIAL_GROUP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PRODUCT_COMBINATION_TYPE_FOR_DELETE
SELECT  INS_PRODUCT_COMBINATION_TYPE.ID 
FROM INS_PRODUCT_COMBINATION_TYPE
WHERE 
[INS_PRODUCT_COMBINATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PFP_VEHICLE_TYPE_FOR_DELETE
SELECT  INS_PFP_VEHICLE_TYPE.ID 
FROM INS_PFP_VEHICLE_TYPE
WHERE 
[INS_PFP_VEHICLE_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PFP_POSITION_FOR_DELETE
SELECT  INS_PFP_POSITION.ID 
FROM INS_PFP_POSITION
WHERE 
[INS_PFP_POSITION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_PFP_INSPECTION_TYPE_FOR_DELETE
SELECT  INS_PFP_INSPECTION_TYPE.ID 
FROM INS_PFP_INSPECTION_TYPE
WHERE 
[INS_PFP_INSPECTION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_OPTICAL_DEFECT_FOR_DELETE
SELECT  INS_OPTICAL_DEFECT.ID 
FROM INS_OPTICAL_DEFECT
WHERE 
[INS_OPTICAL_DEFECT].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_NOT_MEASURABLE_VALUE_FOR_DELETE
SELECT  INS_NOT_MEASURABLE_VALUE.ID 
FROM INS_NOT_MEASURABLE_VALUE
WHERE 
[INS_NOT_MEASURABLE_VALUE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_NEXT_SP_INTERVAL_FOR_DELETE
SELECT  INS_NEXT_SP_INTERVAL.ID 
FROM INS_NEXT_SP_INTERVAL
WHERE 
[INS_NEXT_SP_INTERVAL].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_NEXT_INSPECTION_FOR_DELETE
SELECT  INS_NEXT_INSPECTION.ID 
FROM INS_NEXT_INSPECTION
WHERE 
[INS_NEXT_INSPECTION].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_META_DATA_FOR_DELETE
SELECT  INS_META_DATA.ID 
FROM INS_META_DATA
WHERE 
[INS_META_DATA].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_MEASURE_TYPE_FOR_DELETE
SELECT  INS_MEASURE_TYPE.ID 
FROM INS_MEASURE_TYPE
WHERE 
[INS_MEASURE_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_INSPECTION_STEP_FOR_DELETE
SELECT  INS_INSPECTION_STEP.ID 
FROM INS_INSPECTION_STEP
WHERE 
[INS_INSPECTION_STEP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_INSPECTION_REPORT_STATUS_FOR_DELETE
SELECT  INS_INSPECTION_REPORT_STATUS.ID 
FROM INS_INSPECTION_REPORT_STATUS
WHERE 
[INS_INSPECTION_REPORT_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_EG_DOK_SERVICE_TYPE_FOR_DELETE
SELECT  INS_EG_DOK_SERVICE_TYPE.ID 
FROM INS_EG_DOK_SERVICE_TYPE
WHERE 
[INS_EG_DOK_SERVICE_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_CORE_DATA_PRODUCT_GROUP_FOR_DELETE
SELECT  INS_CORE_DATA_PRODUCT_GROUP.ID 
FROM INS_CORE_DATA_PRODUCT_GROUP
WHERE 
[INS_CORE_DATA_PRODUCT_GROUP].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_BRAKE_INSPECTION_METHOD_FOR_DELETE
SELECT  INS_BRAKE_INSPECTION_METHOD.ID 
FROM INS_BRAKE_INSPECTION_METHOD
WHERE 
[INS_BRAKE_INSPECTION_METHOD].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @INS_AVAILABLE_INSPECTION_TEXT_FOR_DELETE
SELECT  INS_AVAILABLE_INSPECTION_TEXT.ID 
FROM INS_AVAILABLE_INSPECTION_TEXT
WHERE 
[INS_AVAILABLE_INSPECTION_TEXT].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EXP_TRIP_TYPE_FOR_DELETE
SELECT  EXP_TRIP_TYPE.ID 
FROM EXP_TRIP_TYPE
WHERE 
[EXP_TRIP_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EXP_PASSENGERS_TYPE_FOR_DELETE
SELECT  EXP_PASSENGERS_TYPE.ID 
FROM EXP_PASSENGERS_TYPE
WHERE 
[EXP_PASSENGERS_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_EMPLOYEE_INFO_TYPE_FOR_DELETE
SELECT  EMP_EMPLOYEE_INFO_TYPE.ID 
FROM EMP_EMPLOYEE_INFO_TYPE
WHERE 
[EMP_EMPLOYEE_INFO_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

INSERT INTO @EMP_CORE_ADDRESS_TYPE_FOR_DELETE
SELECT  EMP_CORE_ADDRESS_TYPE.ID 
FROM EMP_CORE_ADDRESS_TYPE
WHERE 
[EMP_CORE_ADDRESS_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;


DELETE SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP FROM SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP tab JOIN @SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_ESCALATION_LEVEL FROM SYS_ESCALATION_LEVEL tab JOIN @SYS_ESCALATION_LEVEL_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_DOCUMENT_TEXT_CONFIGURATION FROM SYS_DOCUMENT_TEXT_CONFIGURATION tab JOIN @SYS_DOCUMENT_TEXT_CONFIGURATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_TOP_ORG_UNIT_RSP FROM ORG_UNIT_TOP_ORG_UNIT_RSP tab JOIN @ORG_UNIT_TOP_ORG_UNIT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_ORG_COST_CENTER_RSP FROM ORG_UNIT_ORG_COST_CENTER_RSP tab JOIN @ORG_UNIT_ORG_COST_CENTER_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_OPEN_TIME_RSP FROM ORG_UNIT_OPEN_TIME_RSP tab JOIN @ORG_UNIT_OPEN_TIME_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_INFO_RSP FROM ORG_UNIT_INFO_RSP tab JOIN @ORG_UNIT_INFO_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_FEDERAL_STATE_RSP FROM ORG_UNIT_FEDERAL_STATE_RSP tab JOIN @ORG_UNIT_FEDERAL_STATE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_BANK_INFO_RSP FROM ORG_UNIT_BANK_INFO_RSP tab JOIN @ORG_UNIT_BANK_INFO_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_ADDRESS_RSP FROM ORG_UNIT_ADDRESS_RSP tab JOIN @ORG_UNIT_ADDRESS_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_UNIT_ACCOUNT_TYPE_RSP FROM ORG_UNIT_ACCOUNT_TYPE_RSP tab JOIN @ORG_UNIT_ACCOUNT_TYPE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_ORG_UNIT_RSP FROM ORD_CUSTOMER_ORG_UNIT_RSP tab JOIN @ORD_CUSTOMER_ORG_UNIT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_REPORT_TEXT_CONFIGURATION FROM INS_INSPECTION_REPORT_TEXT_CONFIGURATION tab JOIN @INS_INSPECTION_REPORT_TEXT_CONFIGURATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP FROM EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP tab JOIN @EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP FROM EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP tab JOIN @EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_ORGANIZATIONAL_UNIT FROM ORG_ORGANIZATIONAL_UNIT tab JOIN @ORG_ORGANIZATIONAL_UNIT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP FROM ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP tab JOIN @ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_COST_CENTER_PRICE FROM ORG_COST_CENTER_PRICE tab JOIN @ORG_COST_CENTER_PRICE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_PROVISION_COST FROM ORD_PROVISION_COST tab JOIN @ORD_PROVISION_COST_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_EMAIL FROM ORD_EMAIL tab JOIN @ORD_EMAIL_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_PRICE FROM ORD_CUSTOMER_PRICE tab JOIN @ORD_CUSTOMER_PRICE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SEVERITY_VALID_PERIOD_RSP FROM INS_SEVERITY_VALID_PERIOD_RSP tab JOIN @INS_SEVERITY_VALID_PERIOD_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SEVERITY_NEXT_INSPECTION_RSP FROM INS_SEVERITY_NEXT_INSPECTION_RSP tab JOIN @INS_SEVERITY_NEXT_INSPECTION_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SEVERITY_LABEL_RSP FROM INS_SEVERITY_LABEL_RSP tab JOIN @INS_SEVERITY_LABEL_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_REGION_PRICE FROM INS_PRODUCT_REGION_PRICE tab JOIN @INS_PRODUCT_REGION_PRICE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_PRICE FROM INS_PRODUCT_PRICE tab JOIN @INS_PRODUCT_PRICE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_DISCOUNT FROM INS_PRODUCT_DISCOUNT tab JOIN @INS_PRODUCT_DISCOUNT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP FROM INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP tab JOIN @INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP FROM INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP tab JOIN @INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP FROM INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP tab JOIN @INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP FROM INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP tab JOIN @INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_LOCALIZATION FROM INS_CORE_DATA_PRODUCT_LOCALIZATION tab JOIN @INS_CORE_DATA_PRODUCT_LOCALIZATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO FROM INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO tab JOIN @INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_EXPIRATION_INFO FROM INS_CORE_DATA_PRODUCT_EXPIRATION_INFO tab JOIN @INS_CORE_DATA_PRODUCT_EXPIRATION_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP FROM INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP tab JOIN @INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_TOP_EMPLOYEE_RSP FROM EMP_EMPLOYEE_TOP_EMPLOYEE_RSP tab JOIN @EMP_EMPLOYEE_TOP_EMPLOYEE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_SYS_ROLE_RSP FROM EMP_EMPLOYEE_SYS_ROLE_RSP tab JOIN @EMP_EMPLOYEE_SYS_ROLE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_ORG_COST_CENTER_RSP FROM EMP_EMPLOYEE_ORG_COST_CENTER_RSP tab JOIN @EMP_EMPLOYEE_ORG_COST_CENTER_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_INFO_TYPE_RSP FROM EMP_EMPLOYEE_INFO_TYPE_RSP tab JOIN @EMP_EMPLOYEE_INFO_TYPE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_CASH_PERMISSION FROM EMP_CASH_PERMISSION tab JOIN @EMP_CASH_PERMISSION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_LOCATION FROM SYS_LOCATION tab JOIN @SYS_LOCATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_RECOGNITION_AREA_OF_WORK_RSP FROM ORD_RECOGNITION_AREA_OF_WORK_RSP tab JOIN @ORD_RECOGNITION_AREA_OF_WORK_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_ADDRESS_RSP FROM ORD_CUSTOMER_ADDRESS_RSP tab JOIN @ORD_CUSTOMER_ADDRESS_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_VALID_PERIOD_PRODUCT_CLASS_RSP FROM INS_VALID_PERIOD_PRODUCT_CLASS_RSP tab JOIN @INS_VALID_PERIOD_PRODUCT_CLASS_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_UNIT_CODE FROM INS_UNIT_CODE tab JOIN @INS_UNIT_CODE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SPECIFIC_DATA FROM INS_SPECIFIC_DATA tab JOIN @INS_SPECIFIC_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP FROM INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP tab JOIN @INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP FROM INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP tab JOIN @INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP FROM INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP tab JOIN @INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS_LABEL_RSP FROM INS_PRODUCT_CLASS_LABEL_RSP tab JOIN @INS_PRODUCT_CLASS_LABEL_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP FROM INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP tab JOIN @INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION FROM INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION tab JOIN @INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP FROM INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP tab JOIN @INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP FROM INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP tab JOIN @INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT FROM INS_CORE_DATA_PRODUCT tab JOIN @INS_CORE_DATA_PRODUCT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE FROM EMP_EMPLOYEE tab JOIN @EMP_EMPLOYEE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_CORE_ADDRESS_RECOGNITION_RSP FROM EMP_CORE_ADDRESS_RECOGNITION_RSP tab JOIN @EMP_CORE_ADDRESS_RECOGNITION_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_CORE_ADDRESS_FEDERAL_STATE_RSP FROM EMP_CORE_ADDRESS_FEDERAL_STATE_RSP tab JOIN @EMP_CORE_ADDRESS_FEDERAL_STATE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP FROM VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP tab JOIN @VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_ROLE_SYS_PERMISSION_RSP FROM SYS_ROLE_SYS_PERMISSION_RSP tab JOIN @SYS_ROLE_SYS_PERMISSION_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_NOTIFICATION FROM SYS_NOTIFICATION tab JOIN @SYS_NOTIFICATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_DEFAULT_LANGUAGE FROM SYS_DEFAULT_LANGUAGE tab JOIN @SYS_DEFAULT_LANGUAGE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_RECOGNITION FROM ORD_RECOGNITION tab JOIN @ORD_RECOGNITION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_FEDERAL_STATE FROM ORD_FEDERAL_STATE tab JOIN @ORD_FEDERAL_STATE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_TAX_INFO FROM ORD_CUSTOMER_TAX_INFO tab JOIN @ORD_CUSTOMER_TAX_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_PARTNER_ROLE_RSP FROM ORD_CUSTOMER_PARTNER_ROLE_RSP tab JOIN @ORD_CUSTOMER_PARTNER_ROLE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP FROM ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP tab JOIN @ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_LOCK_INFO FROM ORD_CUSTOMER_LOCK_INFO tab JOIN @ORD_CUSTOMER_LOCK_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_INFO_RSP FROM ORD_CUSTOMER_INFO_RSP tab JOIN @ORD_CUSTOMER_INFO_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_BILLING_PARAMETER_RSP FROM ORD_CUSTOMER_BILLING_PARAMETER_RSP tab JOIN @ORD_CUSTOMER_BILLING_PARAMETER_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CONTACT_PERSON FROM ORD_CONTACT_PERSON tab JOIN @ORD_CONTACT_PERSON_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_EXPENSE_GROUND FROM KSS_EXPENSE_GROUND tab JOIN @KSS_EXPENSE_GROUND_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_TEMPLATE FROM INS_TEMPLATE tab JOIN @INS_TEMPLATE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_TAX_INFO FROM INS_TAX_INFO tab JOIN @INS_TAX_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_COMBINATION FROM INS_PRODUCT_COMBINATION tab JOIN @INS_PRODUCT_COMBINATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_CLASS FROM INS_PRODUCT_CLASS tab JOIN @INS_PRODUCT_CLASS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP FROM INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP tab JOIN @INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_MEASURABLE_VALUE FROM INS_MEASURABLE_VALUE tab JOIN @INS_MEASURABLE_VALUE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_AVAILABLE_INSPECTION_TEXT_VALUE FROM INS_AVAILABLE_INSPECTION_TEXT_VALUE tab JOIN @INS_AVAILABLE_INSPECTION_TEXT_VALUE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_AVAILABLE_INSPECTION_STEP FROM INS_AVAILABLE_INSPECTION_STEP tab JOIN @INS_AVAILABLE_INSPECTION_STEP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_CORE_ADDRESS FROM EMP_CORE_ADDRESS tab JOIN @EMP_CORE_ADDRESS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_SPECIAL_INFO FROM VHL_SPECIAL_INFO tab JOIN @VHL_SPECIAL_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP FROM VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP tab JOIN @VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_COLOR FROM VHL_COLOR tab JOIN @VHL_COLOR_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_ROLE FROM SYS_ROLE tab JOIN @SYS_ROLE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_POST_CODE FROM SYS_POST_CODE tab JOIN @SYS_POST_CODE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_POS_CONFIGURATION FROM SYS_POS_CONFIGURATION tab JOIN @SYS_POS_CONFIGURATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_PERMISSION FROM SYS_PERMISSION tab JOIN @SYS_PERMISSION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_PAPER_TYPE FROM SYS_PAPER_TYPE tab JOIN @SYS_PAPER_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_NOTIFICATION_TYPE FROM SYS_NOTIFICATION_TYPE tab JOIN @SYS_NOTIFICATION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_MODULE FROM SYS_MODULE tab JOIN @SYS_MODULE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_LANGUAGE FROM SYS_LANGUAGE tab JOIN @SYS_LANGUAGE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_INFO_KEY FROM SYS_INFO_KEY tab JOIN @SYS_INFO_KEY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_ENCRYPTION_METADATA FROM SYS_ENCRYPTION_METADATA tab JOIN @SYS_ENCRYPTION_METADATA_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_EMERGENCY_KEY FROM SYS_EMERGENCY_KEY tab JOIN @SYS_EMERGENCY_KEY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_DOCUMENT_TYPE FROM SYS_DOCUMENT_TYPE tab JOIN @SYS_DOCUMENT_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_CURRENCY FROM SYS_CURRENCY tab JOIN @SYS_CURRENCY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_COUNTRY FROM SYS_COUNTRY tab JOIN @SYS_COUNTRY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_CONFIGURATION FROM SYS_CONFIGURATION tab JOIN @SYS_CONFIGURATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_ACTION_TYPE FROM SYS_ACTION_TYPE tab JOIN @SYS_ACTION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_TYPE FROM ORG_TYPE tab JOIN @ORG_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_OPEN_TIME_TYPE FROM ORG_OPEN_TIME_TYPE tab JOIN @ORG_OPEN_TIME_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_INSPECTION_DEVICE FROM ORG_INSPECTION_DEVICE tab JOIN @ORG_INSPECTION_DEVICE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_INFORMATION FROM ORG_INFORMATION tab JOIN @ORG_INFORMATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_COST_CENTER FROM ORG_COST_CENTER tab JOIN @ORG_COST_CENTER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_BANK_INFORMATION FROM ORG_BANK_INFORMATION tab JOIN @ORG_BANK_INFORMATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_ACCOUNTING_AREA FROM ORG_ACCOUNTING_AREA tab JOIN @ORG_ACCOUNTING_AREA_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORG_ACCOUNT_TYPE FROM ORG_ACCOUNT_TYPE tab JOIN @ORG_ACCOUNT_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_SAP_STATUS FROM ORD_SAP_STATUS tab JOIN @ORD_SAP_STATUS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_RECOGNITION_TYPE FROM ORD_RECOGNITION_TYPE tab JOIN @ORD_RECOGNITION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_PRODUCT_STATUS FROM ORD_PRODUCT_STATUS tab JOIN @ORD_PRODUCT_STATUS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_PARTNER_ROLE FROM ORD_PARTNER_ROLE tab JOIN @ORD_PARTNER_ROLE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ORDER_TYPE FROM ORD_ORDER_TYPE tab JOIN @ORD_ORDER_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ORDER_STATUS FROM ORD_ORDER_STATUS tab JOIN @ORD_ORDER_STATUS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ORDER_CANCELATION_REASON FROM ORD_ORDER_CANCELATION_REASON tab JOIN @ORD_ORDER_CANCELATION_REASON_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ORDER_ADDITIONAL_INFORMATION_TYPE FROM ORD_ORDER_ADDITIONAL_INFORMATION_TYPE tab JOIN @ORD_ORDER_ADDITIONAL_INFORMATION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ESCALATION_LEVEL_ACTION FROM ORD_ESCALATION_LEVEL_ACTION tab JOIN @ORD_ESCALATION_LEVEL_ACTION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER_INFO FROM ORD_CUSTOMER_INFO tab JOIN @ORD_CUSTOMER_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CUSTOMER FROM ORD_CUSTOMER tab JOIN @ORD_CUSTOMER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_CONTACT_PERSON_FUNCTION FROM ORD_CONTACT_PERSON_FUNCTION tab JOIN @ORD_CONTACT_PERSON_FUNCTION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_BILLING_PARAMETER FROM ORD_BILLING_PARAMETER tab JOIN @ORD_BILLING_PARAMETER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_BILL_TYPE FROM ORD_BILL_TYPE tab JOIN @ORD_BILL_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_AREA_OF_WORK FROM ORD_AREA_OF_WORK tab JOIN @ORD_AREA_OF_WORK_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ADDITIONAL_PAYMENTS FROM ORD_ADDITIONAL_PAYMENTS tab JOIN @ORD_ADDITIONAL_PAYMENTS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_PAYMENT_METHOD FROM KSS_PAYMENT_METHOD tab JOIN @KSS_PAYMENT_METHOD_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_OPERATION_TYPE FROM KSS_OPERATION_TYPE tab JOIN @KSS_OPERATION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_OPERATION_STATUS FROM KSS_OPERATION_STATUS tab JOIN @KSS_OPERATION_STATUS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_DOCUMENT_TYPE FROM KSS_DOCUMENT_TYPE tab JOIN @KSS_DOCUMENT_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_CASH_STATUS FROM KSS_CASH_STATUS tab JOIN @KSS_CASH_STATUS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_VAT_TYPE FROM INS_VAT_TYPE tab JOIN @INS_VAT_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_VALID_PERIOD FROM INS_VALID_PERIOD tab JOIN @INS_VALID_PERIOD_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_TAX_CODE FROM INS_TAX_CODE tab JOIN @INS_TAX_CODE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_TAX_CLASS FROM INS_TAX_CLASS tab JOIN @INS_TAX_CLASS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SUMMARY_FIELD FROM INS_SUMMARY_FIELD tab JOIN @INS_SUMMARY_FIELD_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_SEVERITY_TYPE FROM INS_SEVERITY_TYPE tab JOIN @INS_SEVERITY_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_TYPE FROM INS_PRODUCT_TYPE tab JOIN @INS_PRODUCT_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_OBJECT_TYPE FROM INS_PRODUCT_OBJECT_TYPE tab JOIN @INS_PRODUCT_OBJECT_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_OBJECT_CLASS FROM INS_PRODUCT_OBJECT_CLASS tab JOIN @INS_PRODUCT_OBJECT_CLASS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_MATERIAL_GROUP FROM INS_PRODUCT_MATERIAL_GROUP tab JOIN @INS_PRODUCT_MATERIAL_GROUP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PRODUCT_COMBINATION_TYPE FROM INS_PRODUCT_COMBINATION_TYPE tab JOIN @INS_PRODUCT_COMBINATION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PFP_VEHICLE_TYPE FROM INS_PFP_VEHICLE_TYPE tab JOIN @INS_PFP_VEHICLE_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PFP_POSITION FROM INS_PFP_POSITION tab JOIN @INS_PFP_POSITION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PFP_INSPECTION_TYPE FROM INS_PFP_INSPECTION_TYPE tab JOIN @INS_PFP_INSPECTION_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_OPTICAL_DEFECT FROM INS_OPTICAL_DEFECT tab JOIN @INS_OPTICAL_DEFECT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_NOT_MEASURABLE_VALUE FROM INS_NOT_MEASURABLE_VALUE tab JOIN @INS_NOT_MEASURABLE_VALUE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_NEXT_SP_INTERVAL FROM INS_NEXT_SP_INTERVAL tab JOIN @INS_NEXT_SP_INTERVAL_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_NEXT_INSPECTION FROM INS_NEXT_INSPECTION tab JOIN @INS_NEXT_INSPECTION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_META_DATA FROM INS_META_DATA tab JOIN @INS_META_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_MEASURE_TYPE FROM INS_MEASURE_TYPE tab JOIN @INS_MEASURE_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_STEP FROM INS_INSPECTION_STEP tab JOIN @INS_INSPECTION_STEP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_REPORT_STATUS FROM INS_INSPECTION_REPORT_STATUS tab JOIN @INS_INSPECTION_REPORT_STATUS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_EG_DOK_SERVICE_TYPE FROM INS_EG_DOK_SERVICE_TYPE tab JOIN @INS_EG_DOK_SERVICE_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_CORE_DATA_PRODUCT_GROUP FROM INS_CORE_DATA_PRODUCT_GROUP tab JOIN @INS_CORE_DATA_PRODUCT_GROUP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_BRAKE_INSPECTION_METHOD FROM INS_BRAKE_INSPECTION_METHOD tab JOIN @INS_BRAKE_INSPECTION_METHOD_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_AVAILABLE_INSPECTION_TEXT FROM INS_AVAILABLE_INSPECTION_TEXT tab JOIN @INS_AVAILABLE_INSPECTION_TEXT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EXP_TRIP_TYPE FROM EXP_TRIP_TYPE tab JOIN @EXP_TRIP_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EXP_PASSENGERS_TYPE FROM EXP_PASSENGERS_TYPE tab JOIN @EXP_PASSENGERS_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_EMPLOYEE_INFO_TYPE FROM EMP_EMPLOYEE_INFO_TYPE tab JOIN @EMP_EMPLOYEE_INFO_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_CORE_ADDRESS_TYPE FROM EMP_CORE_ADDRESS_TYPE tab JOIN @EMP_CORE_ADDRESS_TYPE_FOR_DELETE idlist ON tab.ID = idlist.ID
