SELECT  EMP_CORE_ADDRESS_TYPE.* 
FROM EMP_CORE_ADDRESS_TYPE
WHERE 
[EMP_CORE_ADDRESS_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_INFO_TYPE.* 
FROM EMP_EMPLOYEE_INFO_TYPE
WHERE 
[EMP_EMPLOYEE_INFO_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EXP_PASSENGERS_TYPE.* 
FROM EXP_PASSENGERS_TYPE
WHERE 
[EXP_PASSENGERS_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EXP_TRIP_TYPE.* 
FROM EXP_TRIP_TYPE
WHERE 
[EXP_TRIP_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_AVAILABLE_INSPECTION_TEXT.* 
FROM INS_AVAILABLE_INSPECTION_TEXT
WHERE 
[INS_AVAILABLE_INSPECTION_TEXT].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_BRAKE_INSPECTION_METHOD.* 
FROM INS_BRAKE_INSPECTION_METHOD
WHERE 
[INS_BRAKE_INSPECTION_METHOD].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_GROUP.* 
FROM INS_CORE_DATA_PRODUCT_GROUP
WHERE 
[INS_CORE_DATA_PRODUCT_GROUP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_EG_DOK_SERVICE_TYPE.* 
FROM INS_EG_DOK_SERVICE_TYPE
WHERE 
[INS_EG_DOK_SERVICE_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_INSPECTION_REPORT_STATUS.* 
FROM INS_INSPECTION_REPORT_STATUS
WHERE 
[INS_INSPECTION_REPORT_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_INSPECTION_STEP.* 
FROM INS_INSPECTION_STEP
WHERE 
[INS_INSPECTION_STEP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_MEASURE_TYPE.* 
FROM INS_MEASURE_TYPE
WHERE 
[INS_MEASURE_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_META_DATA.* 
FROM INS_META_DATA
WHERE 
[INS_META_DATA].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_NEXT_INSPECTION.* 
FROM INS_NEXT_INSPECTION
WHERE 
[INS_NEXT_INSPECTION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_NEXT_SP_INTERVAL.* 
FROM INS_NEXT_SP_INTERVAL
WHERE 
[INS_NEXT_SP_INTERVAL].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_NOT_MEASURABLE_VALUE.* 
FROM INS_NOT_MEASURABLE_VALUE
WHERE 
[INS_NOT_MEASURABLE_VALUE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_OPTICAL_DEFECT.* 
FROM INS_OPTICAL_DEFECT
WHERE 
[INS_OPTICAL_DEFECT].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PFP_INSPECTION_TYPE.* 
FROM INS_PFP_INSPECTION_TYPE
WHERE 
[INS_PFP_INSPECTION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PFP_POSITION.* 
FROM INS_PFP_POSITION
WHERE 
[INS_PFP_POSITION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PFP_VEHICLE_TYPE.* 
FROM INS_PFP_VEHICLE_TYPE
WHERE 
[INS_PFP_VEHICLE_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_COMBINATION_TYPE.* 
FROM INS_PRODUCT_COMBINATION_TYPE
WHERE 
[INS_PRODUCT_COMBINATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_MATERIAL_GROUP.* 
FROM INS_PRODUCT_MATERIAL_GROUP
WHERE 
[INS_PRODUCT_MATERIAL_GROUP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_OBJECT_CLASS.* 
FROM INS_PRODUCT_OBJECT_CLASS
WHERE 
[INS_PRODUCT_OBJECT_CLASS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_OBJECT_TYPE.* 
FROM INS_PRODUCT_OBJECT_TYPE
WHERE 
[INS_PRODUCT_OBJECT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_TYPE.* 
FROM INS_PRODUCT_TYPE
WHERE 
[INS_PRODUCT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SEVERITY_TYPE.* 
FROM INS_SEVERITY_TYPE
WHERE 
[INS_SEVERITY_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SUMMARY_FIELD.* 
FROM INS_SUMMARY_FIELD
WHERE 
[INS_SUMMARY_FIELD].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_TAX_CLASS.* 
FROM INS_TAX_CLASS
WHERE 
[INS_TAX_CLASS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_TAX_CODE.* 
FROM INS_TAX_CODE
WHERE 
[INS_TAX_CODE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_VALID_PERIOD.* 
FROM INS_VALID_PERIOD
WHERE 
[INS_VALID_PERIOD].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_VAT_TYPE.* 
FROM INS_VAT_TYPE
WHERE 
[INS_VAT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  KSS_CASH_STATUS.* 
FROM KSS_CASH_STATUS
WHERE 
[KSS_CASH_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  KSS_DOCUMENT_TYPE.* 
FROM KSS_DOCUMENT_TYPE
WHERE 
[KSS_DOCUMENT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  KSS_OPERATION_STATUS.* 
FROM KSS_OPERATION_STATUS
WHERE 
[KSS_OPERATION_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  KSS_OPERATION_TYPE.* 
FROM KSS_OPERATION_TYPE
WHERE 
[KSS_OPERATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  KSS_PAYMENT_METHOD.* 
FROM KSS_PAYMENT_METHOD
WHERE 
[KSS_PAYMENT_METHOD].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_ADDITIONAL_PAYMENTS.* 
FROM ORD_ADDITIONAL_PAYMENTS
WHERE 
[ORD_ADDITIONAL_PAYMENTS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_AREA_OF_WORK.* 
FROM ORD_AREA_OF_WORK
WHERE 
[ORD_AREA_OF_WORK].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_BILL_TYPE.* 
FROM ORD_BILL_TYPE
WHERE 
[ORD_BILL_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_BILLING_PARAMETER.* 
FROM ORD_BILLING_PARAMETER
WHERE 
[ORD_BILLING_PARAMETER].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CONTACT_PERSON_FUNCTION.* 
FROM ORD_CONTACT_PERSON_FUNCTION
WHERE 
[ORD_CONTACT_PERSON_FUNCTION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER.* 
FROM ORD_CUSTOMER
WHERE 
[ORD_CUSTOMER].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_INFO.* 
FROM ORD_CUSTOMER_INFO
WHERE 
[ORD_CUSTOMER_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_ESCALATION_LEVEL_ACTION.* 
FROM ORD_ESCALATION_LEVEL_ACTION
WHERE 
[ORD_ESCALATION_LEVEL_ACTION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_ORDER_ADDITIONAL_INFORMATION_TYPE.* 
FROM ORD_ORDER_ADDITIONAL_INFORMATION_TYPE
WHERE 
[ORD_ORDER_ADDITIONAL_INFORMATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_ORDER_CANCELATION_REASON.* 
FROM ORD_ORDER_CANCELATION_REASON
WHERE 
[ORD_ORDER_CANCELATION_REASON].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_ORDER_STATUS.* 
FROM ORD_ORDER_STATUS
WHERE 
[ORD_ORDER_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_ORDER_TYPE.* 
FROM ORD_ORDER_TYPE
WHERE 
[ORD_ORDER_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_PARTNER_ROLE.* 
FROM ORD_PARTNER_ROLE
WHERE 
[ORD_PARTNER_ROLE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_PRODUCT_STATUS.* 
FROM ORD_PRODUCT_STATUS
WHERE 
[ORD_PRODUCT_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_RECOGNITION_TYPE.* 
FROM ORD_RECOGNITION_TYPE
WHERE 
[ORD_RECOGNITION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_SAP_STATUS.* 
FROM ORD_SAP_STATUS
WHERE 
[ORD_SAP_STATUS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_ACCOUNT_TYPE.* 
FROM ORG_ACCOUNT_TYPE
WHERE 
[ORG_ACCOUNT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_ACCOUNTING_AREA.* 
FROM ORG_ACCOUNTING_AREA
WHERE 
[ORG_ACCOUNTING_AREA].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_BANK_INFORMATION.* 
FROM ORG_BANK_INFORMATION
WHERE 
[ORG_BANK_INFORMATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_COST_CENTER.* 
FROM ORG_COST_CENTER
WHERE 
[ORG_COST_CENTER].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_INFORMATION.* 
FROM ORG_INFORMATION
WHERE 
[ORG_INFORMATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_INSPECTION_DEVICE.* 
FROM ORG_INSPECTION_DEVICE
WHERE 
[ORG_INSPECTION_DEVICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_OPEN_TIME_TYPE.* 
FROM ORG_OPEN_TIME_TYPE
WHERE 
[ORG_OPEN_TIME_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_TYPE.* 
FROM ORG_TYPE
WHERE 
[ORG_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_ACTION_TYPE.* 
FROM SYS_ACTION_TYPE
WHERE 
[SYS_ACTION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_CONFIGURATION.* 
FROM SYS_CONFIGURATION
WHERE 
[SYS_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_COUNTRY.* 
FROM SYS_COUNTRY
WHERE 
[SYS_COUNTRY].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_CURRENCY.* 
FROM SYS_CURRENCY
WHERE 
[SYS_CURRENCY].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_DOCUMENT_TYPE.* 
FROM SYS_DOCUMENT_TYPE
WHERE 
[SYS_DOCUMENT_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_EMERGENCY_KEY.* 
FROM SYS_EMERGENCY_KEY
WHERE 
[SYS_EMERGENCY_KEY].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_ENCRYPTION_METADATA.* 
FROM SYS_ENCRYPTION_METADATA
WHERE 
[SYS_ENCRYPTION_METADATA].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_INFO_KEY.* 
FROM SYS_INFO_KEY
WHERE 
[SYS_INFO_KEY].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_LANGUAGE.* 
FROM SYS_LANGUAGE
WHERE 
[SYS_LANGUAGE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_MODULE.* 
FROM SYS_MODULE
WHERE 
[SYS_MODULE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_NOTIFICATION_TYPE.* 
FROM SYS_NOTIFICATION_TYPE
WHERE 
[SYS_NOTIFICATION_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_PAPER_TYPE.* 
FROM SYS_PAPER_TYPE
WHERE 
[SYS_PAPER_TYPE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_PERMISSION.* 
FROM SYS_PERMISSION
WHERE 
[SYS_PERMISSION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_POS_CONFIGURATION.* 
FROM SYS_POS_CONFIGURATION
WHERE 
[SYS_POS_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_POST_CODE.* 
FROM SYS_POST_CODE
WHERE 
[SYS_POST_CODE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_ROLE.* 
FROM SYS_ROLE
WHERE 
[SYS_ROLE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  VHL_COLOR.* 
FROM VHL_COLOR
WHERE 
[VHL_COLOR].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP.* 
FROM VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP
WHERE 
[VHL_FUEL_TYPE_FORBIDDEN_INSPECTION_PRODUCT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  VHL_SPECIAL_INFO.* 
FROM VHL_SPECIAL_INFO
WHERE 
[VHL_SPECIAL_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_CORE_ADDRESS.* 
FROM EMP_CORE_ADDRESS
WHERE 
[EMP_CORE_ADDRESS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_AVAILABLE_INSPECTION_STEP.* 
FROM INS_AVAILABLE_INSPECTION_STEP
WHERE 
[INS_AVAILABLE_INSPECTION_STEP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_AVAILABLE_INSPECTION_TEXT_VALUE.* 
FROM INS_AVAILABLE_INSPECTION_TEXT_VALUE
WHERE 
[INS_AVAILABLE_INSPECTION_TEXT_VALUE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_MEASURABLE_VALUE.* 
FROM INS_MEASURABLE_VALUE
WHERE 
[INS_MEASURABLE_VALUE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP.* 
FROM INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP
WHERE 
[INS_PFP_INSPECTION_TYPE_PFP_POSITION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS.* 
FROM INS_PRODUCT_CLASS
WHERE 
[INS_PRODUCT_CLASS].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_COMBINATION.* 
FROM INS_PRODUCT_COMBINATION
WHERE 
[INS_PRODUCT_COMBINATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_TAX_INFO.* 
FROM INS_TAX_INFO
WHERE 
[INS_TAX_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_TEMPLATE.* 
FROM INS_TEMPLATE
WHERE 
[INS_TEMPLATE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  KSS_EXPENSE_GROUND.* 
FROM KSS_EXPENSE_GROUND
WHERE 
[KSS_EXPENSE_GROUND].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CONTACT_PERSON.* 
FROM ORD_CONTACT_PERSON
WHERE 
[ORD_CONTACT_PERSON].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_BILLING_PARAMETER_RSP.* 
FROM ORD_CUSTOMER_BILLING_PARAMETER_RSP
WHERE 
[ORD_CUSTOMER_BILLING_PARAMETER_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_INFO_RSP.* 
FROM ORD_CUSTOMER_INFO_RSP
WHERE 
[ORD_CUSTOMER_INFO_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_LOCK_INFO.* 
FROM ORD_CUSTOMER_LOCK_INFO
WHERE 
[ORD_CUSTOMER_LOCK_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP.* 
FROM ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP
WHERE 
[ORD_CUSTOMER_ORG_ACCOUNT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_PARTNER_ROLE_RSP.* 
FROM ORD_CUSTOMER_PARTNER_ROLE_RSP
WHERE 
[ORD_CUSTOMER_PARTNER_ROLE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_TAX_INFO.* 
FROM ORD_CUSTOMER_TAX_INFO
WHERE 
[ORD_CUSTOMER_TAX_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_FEDERAL_STATE.* 
FROM ORD_FEDERAL_STATE
WHERE 
[ORD_FEDERAL_STATE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_RECOGNITION.* 
FROM ORD_RECOGNITION
WHERE 
[ORD_RECOGNITION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_DEFAULT_LANGUAGE.* 
FROM SYS_DEFAULT_LANGUAGE
WHERE 
[SYS_DEFAULT_LANGUAGE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_NOTIFICATION.* 
FROM SYS_NOTIFICATION
WHERE 
[SYS_NOTIFICATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_ROLE_SYS_PERMISSION_RSP.* 
FROM SYS_ROLE_SYS_PERMISSION_RSP
WHERE 
[SYS_ROLE_SYS_PERMISSION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP.* 
FROM VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP
WHERE 
[VHL_CLASS_INS_PRODUCT_OBJECT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_CORE_ADDRESS_FEDERAL_STATE_RSP.* 
FROM EMP_CORE_ADDRESS_FEDERAL_STATE_RSP
WHERE 
[EMP_CORE_ADDRESS_FEDERAL_STATE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_CORE_ADDRESS_RECOGNITION_RSP.* 
FROM EMP_CORE_ADDRESS_RECOGNITION_RSP
WHERE 
[EMP_CORE_ADDRESS_RECOGNITION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE.* 
FROM EMP_EMPLOYEE
WHERE 
[EMP_EMPLOYEE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT.* 
FROM INS_CORE_DATA_PRODUCT
WHERE 
[INS_CORE_DATA_PRODUCT].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP.* 
FROM INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP
WHERE 
[INS_NEXT_INSPECTION_PRODUCT_CLASS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP.* 
FROM INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP
WHERE 
[INS_PRODUCT_CLASS_AVAILABLE_INSPECTION_STEP_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION.* 
FROM INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION
WHERE 
[INS_PRODUCT_CLASS_DEFECT_IDENTIFICATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP.* 
FROM INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP
WHERE 
[INS_PRODUCT_CLASS_INSPECTION_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS_LABEL_RSP.* 
FROM INS_PRODUCT_CLASS_LABEL_RSP
WHERE 
[INS_PRODUCT_CLASS_LABEL_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP.* 
FROM INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP
WHERE 
[INS_PRODUCT_CLASS_RECEIPT_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP.* 
FROM INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP
WHERE 
[INS_RESULT_COMBINATION_AVALIABLE_INSPECTION_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP.* 
FROM INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP
WHERE 
[INS_SEVERITY_TYPE_PRODUCT_CLASS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SPECIFIC_DATA.* 
FROM INS_SPECIFIC_DATA
WHERE 
[INS_SPECIFIC_DATA].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_UNIT_CODE.* 
FROM INS_UNIT_CODE
WHERE 
[INS_UNIT_CODE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_VALID_PERIOD_PRODUCT_CLASS_RSP.* 
FROM INS_VALID_PERIOD_PRODUCT_CLASS_RSP
WHERE 
[INS_VALID_PERIOD_PRODUCT_CLASS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_ADDRESS_RSP.* 
FROM ORD_CUSTOMER_ADDRESS_RSP
WHERE 
[ORD_CUSTOMER_ADDRESS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_RECOGNITION_AREA_OF_WORK_RSP.* 
FROM ORD_RECOGNITION_AREA_OF_WORK_RSP
WHERE 
[ORD_RECOGNITION_AREA_OF_WORK_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_LOCATION.* 
FROM SYS_LOCATION
WHERE 
[SYS_LOCATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_CASH_PERMISSION.* 
FROM EMP_CASH_PERMISSION
WHERE 
[EMP_CASH_PERMISSION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_INFO_TYPE_RSP.* 
FROM EMP_EMPLOYEE_INFO_TYPE_RSP
WHERE 
[EMP_EMPLOYEE_INFO_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_ORG_COST_CENTER_RSP.* 
FROM EMP_EMPLOYEE_ORG_COST_CENTER_RSP
WHERE 
[EMP_EMPLOYEE_ORG_COST_CENTER_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_SYS_ROLE_RSP.* 
FROM EMP_EMPLOYEE_SYS_ROLE_RSP
WHERE 
[EMP_EMPLOYEE_SYS_ROLE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_TOP_EMPLOYEE_RSP.* 
FROM EMP_EMPLOYEE_TOP_EMPLOYEE_RSP
WHERE 
[EMP_EMPLOYEE_TOP_EMPLOYEE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP.* 
FROM INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_ADDITIONAL_PRODUCT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_EXPIRATION_INFO.* 
FROM INS_CORE_DATA_PRODUCT_EXPIRATION_INFO
WHERE 
[INS_CORE_DATA_PRODUCT_EXPIRATION_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO.* 
FROM INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO
WHERE 
[INS_CORE_DATA_PRODUCT_INSPECTION_LOCATION_INFO].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_LOCALIZATION.* 
FROM INS_CORE_DATA_PRODUCT_LOCALIZATION
WHERE 
[INS_CORE_DATA_PRODUCT_LOCALIZATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP.* 
FROM INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_PFP_POSITION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP.* 
FROM INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_PFP_VEHICLE_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP.* 
FROM INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP
WHERE 
[INS_CORE_DATA_PRODUCT_RECEIPT_TEXT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP.* 
FROM INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP
WHERE 
[INS_PRODUCT_CLASS_SUMMARY_FIELD_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_DISCOUNT.* 
FROM INS_PRODUCT_DISCOUNT
WHERE 
[INS_PRODUCT_DISCOUNT].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_PRICE.* 
FROM INS_PRODUCT_PRICE
WHERE 
[INS_PRODUCT_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_PRODUCT_REGION_PRICE.* 
FROM INS_PRODUCT_REGION_PRICE
WHERE 
[INS_PRODUCT_REGION_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SEVERITY_LABEL_RSP.* 
FROM INS_SEVERITY_LABEL_RSP
WHERE 
[INS_SEVERITY_LABEL_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SEVERITY_NEXT_INSPECTION_RSP.* 
FROM INS_SEVERITY_NEXT_INSPECTION_RSP
WHERE 
[INS_SEVERITY_NEXT_INSPECTION_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_SEVERITY_VALID_PERIOD_RSP.* 
FROM INS_SEVERITY_VALID_PERIOD_RSP
WHERE 
[INS_SEVERITY_VALID_PERIOD_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_PRICE.* 
FROM ORD_CUSTOMER_PRICE
WHERE 
[ORD_CUSTOMER_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_EMAIL.* 
FROM ORD_EMAIL
WHERE 
[ORD_EMAIL].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_PROVISION_COST.* 
FROM ORD_PROVISION_COST
WHERE 
[ORD_PROVISION_COST].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_COST_CENTER_PRICE.* 
FROM ORG_COST_CENTER_PRICE
WHERE 
[ORG_COST_CENTER_PRICE].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP.* 
FROM ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP
WHERE 
[ORG_COST_CENTER_RESPONSIBLE_EMPLOYEE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_ORGANIZATIONAL_UNIT.* 
FROM ORG_ORGANIZATIONAL_UNIT
WHERE 
[ORG_ORGANIZATIONAL_UNIT].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP.* 
FROM EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP
WHERE 
[EMP_EMPLOYEE_ORG_ORGANIZATIONAL_UNIT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP.* 
FROM EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP
WHERE 
[EMP_EMPLOYEE_ORGANIZATIONAL_UNIT_ORDER_LOOKUP_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  INS_INSPECTION_REPORT_TEXT_CONFIGURATION.* 
FROM INS_INSPECTION_REPORT_TEXT_CONFIGURATION
WHERE 
[INS_INSPECTION_REPORT_TEXT_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORD_CUSTOMER_ORG_UNIT_RSP.* 
FROM ORD_CUSTOMER_ORG_UNIT_RSP
WHERE 
[ORD_CUSTOMER_ORG_UNIT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_ACCOUNT_TYPE_RSP.* 
FROM ORG_UNIT_ACCOUNT_TYPE_RSP
WHERE 
[ORG_UNIT_ACCOUNT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_ADDRESS_RSP.* 
FROM ORG_UNIT_ADDRESS_RSP
WHERE 
[ORG_UNIT_ADDRESS_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_BANK_INFO_RSP.* 
FROM ORG_UNIT_BANK_INFO_RSP
WHERE 
[ORG_UNIT_BANK_INFO_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_FEDERAL_STATE_RSP.* 
FROM ORG_UNIT_FEDERAL_STATE_RSP
WHERE 
[ORG_UNIT_FEDERAL_STATE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_INFO_RSP.* 
FROM ORG_UNIT_INFO_RSP
WHERE 
[ORG_UNIT_INFO_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_OPEN_TIME_RSP.* 
FROM ORG_UNIT_OPEN_TIME_RSP
WHERE 
[ORG_UNIT_OPEN_TIME_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_ORG_COST_CENTER_RSP.* 
FROM ORG_UNIT_ORG_COST_CENTER_RSP
WHERE 
[ORG_UNIT_ORG_COST_CENTER_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  ORG_UNIT_TOP_ORG_UNIT_RSP.* 
FROM ORG_UNIT_TOP_ORG_UNIT_RSP
WHERE 
[ORG_UNIT_TOP_ORG_UNIT_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_DOCUMENT_TEXT_CONFIGURATION.* 
FROM SYS_DOCUMENT_TEXT_CONFIGURATION
WHERE 
[SYS_DOCUMENT_TEXT_CONFIGURATION].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_ESCALATION_LEVEL.* 
FROM SYS_ESCALATION_LEVEL
WHERE 
[SYS_ESCALATION_LEVEL].[ROW_VERSION] BETWEEN {0} AND {1}
;

SELECT  SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP.* 
FROM SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP
WHERE 
[SYS_DOCUMENT_TEXT_CONFIGURATION_DOCUMENT_TYPE_RSP].[ROW_VERSION] BETWEEN {0} AND {1}
;
