SELECT DISTINCT EXP_WORKING_DAY1.* 
FROM EXP_WORKING_DAY AS EXP_WORKING_DAY1
 JOIN EXP_WORKING_SPAN AS EXP_WORKING_SPAN1 ON EXP_WORKING_DAY1.ID = EXP_WORKING_SPAN1.EXP_WORKING_DAY_ID
WHERE 
[EXP_WORKING_SPAN1].[SYS_SYNC_STATUS_ID] = {1}
AND [EXP_WORKING_SPAN1].[CREATE_EMPLOYEE_ID] = {2}

UNION

SELECT DISTINCT EXP_WORKING_DAY.* 
FROM EXP_WORKING_DAY
WHERE 
[EXP_WORKING_DAY].[ID] IN ({0})
;

SELECT DISTINCT EXP_TRIP.* 
FROM EXP_TRIP
WHERE 
[EXP_TRIP].[SYS_SYNC_STATUS_ID] = {1}
AND [EXP_TRIP].[EXP_WORKING_DAY_ID] IN ({0})
;

SELECT DISTINCT EXP_WORKING_SPAN1.* 
FROM EXP_WORKING_SPAN AS EXP_WORKING_SPAN1
WHERE 
[EXP_WORKING_SPAN1].[SYS_SYNC_STATUS_ID] = {1}
AND [EXP_WORKING_SPAN1].[CREATE_EMPLOYEE_ID] = {2}

UNION

SELECT DISTINCT EXP_WORKING_SPAN.* 
FROM EXP_WORKING_SPAN
WHERE 
[EXP_WORKING_SPAN].[SYS_SYNC_STATUS_ID] = {1}
AND [EXP_WORKING_SPAN].[EXP_WORKING_DAY_ID] IN ({0})
;
