DECLARE @ORD_VEHICLE_ORDER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_SALE_OF_GOODS_ORDER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_PRODUCT_HISTORY_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_POSITION_EXECUTABLE_INS_STEPS_RSP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_POSITION_CASH_NUMBER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_DISCOUNT_INFO_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_DEVICE_ORDER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_POSITION_COMMON_BINARY_DATA_RSP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_EMPLOYEE_PROPORTION_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @VHL_SPECIAL_INFO_READ_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_POSITION_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_ORDER_ADDITIONAL_INFORMATION_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_HOLDER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_ORDER_INSPECTION_TEXT_RSP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_ORDER_COMMON_BINARY_DATA_RSP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @VHL_VEHICLE_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @VHL_AXLE_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_ORDER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_PFP_NOTE_DEFECT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_PFP_DEFECT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_OTHER_VALUE_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_MEASURED_VALUE_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_INSPECTION_REPORT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_FOUND_OPTICAL_DEFECT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_FOUND_DEFECT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_EXECUTABLE_INSPECTION_STEP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_EG_DOC_VEHICLE_DATA_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_ASA_PROBE_SIGNAL_DATA_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_ASA_ERROR_DATA_FOR_DELETE TABLE(ID uniqueidentifier)

DECLARE @ORD_PERSON_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_INSPECTION_RESULT_FOR_DELETE TABLE(ID uniqueidentifier)

DECLARE @ORD_DEVICE_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @ORD_ADDRESS_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_INSPECTION_TEXT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_INSPECTION_LABEL_FOR_DELETE TABLE(ID uniqueidentifier)

DECLARE @INS_COMMON_BINARY_DATA_FOR_DELETE TABLE(ID uniqueidentifier)


DECLARE @VHL_MILE_AGE_FOR_DELETE TABLE(ID uniqueidentifier)




DECLARE @ORD_ORDER_HISTORY_FOR_DELETE TABLE(ID uniqueidentifier)

DECLARE @ORD_ACCOUNT_PARAMETER_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @INS_INSPECTION_REPORT_BINARY_DATA_FOR_DELETE TABLE(ID uniqueidentifier)

INSERT INTO @ORD_VEHICLE_ORDER_FOR_DELETE
SELECT DISTINCT ORD_VEHICLE_ORDER.ID 
FROM ORD_VEHICLE_ORDER
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_SALE_OF_GOODS_ORDER_FOR_DELETE
SELECT DISTINCT ORD_SALE_OF_GOODS_ORDER.ID 
FROM ORD_SALE_OF_GOODS_ORDER
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_PRODUCT_HISTORY_FOR_DELETE
SELECT DISTINCT ORD_PRODUCT_HISTORY.ID 
FROM ORD_PRODUCT_HISTORY
 JOIN ORD_POSITION ON ORD_PRODUCT_HISTORY.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_POSITION_EXECUTABLE_INS_STEPS_RSP_FOR_DELETE
SELECT DISTINCT ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.ID 
FROM ORD_POSITION_EXECUTABLE_INS_STEPS_RSP
 JOIN ORD_POSITION ON ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_POSITION_CASH_NUMBER_FOR_DELETE
SELECT DISTINCT ORD_POSITION_CASH_NUMBER.ID 
FROM ORD_POSITION_CASH_NUMBER
 JOIN ORD_POSITION ON ORD_POSITION_CASH_NUMBER.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_DISCOUNT_INFO_FOR_DELETE
SELECT DISTINCT ORD_DISCOUNT_INFO.ID 
FROM ORD_DISCOUNT_INFO
 JOIN ORD_POSITION ON ORD_DISCOUNT_INFO.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_DEVICE_ORDER_FOR_DELETE
SELECT DISTINCT ORD_DEVICE_ORDER.ID 
FROM ORD_DEVICE_ORDER
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_POSITION_COMMON_BINARY_DATA_RSP_FOR_DELETE
SELECT DISTINCT INS_POSITION_COMMON_BINARY_DATA_RSP.ID 
FROM INS_POSITION_COMMON_BINARY_DATA_RSP
 JOIN ORD_POSITION ON INS_POSITION_COMMON_BINARY_DATA_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP_FOR_DELETE
SELECT DISTINCT INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.ID 
FROM INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP
 JOIN ORD_POSITION ON INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_EMPLOYEE_PROPORTION_FOR_DELETE
SELECT DISTINCT INS_EMPLOYEE_PROPORTION.ID 
FROM INS_EMPLOYEE_PROPORTION
 JOIN ORD_POSITION ON INS_EMPLOYEE_PROPORTION.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @VHL_SPECIAL_INFO_READ_FOR_DELETE
SELECT DISTINCT VHL_SPECIAL_INFO_READ.ID 
FROM VHL_SPECIAL_INFO_READ
WHERE 
[VHL_SPECIAL_INFO_READ].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_POSITION_FOR_DELETE
SELECT DISTINCT ORD_POSITION.ID 
FROM ORD_POSITION
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_ORDER_ADDITIONAL_INFORMATION_FOR_DELETE
SELECT DISTINCT ORD_ORDER_ADDITIONAL_INFORMATION.ID 
FROM ORD_ORDER_ADDITIONAL_INFORMATION
WHERE 
[ORD_ORDER_ADDITIONAL_INFORMATION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_HOLDER_FOR_DELETE
SELECT DISTINCT ORD_HOLDER.ID 
FROM ORD_HOLDER
 JOIN ORD_DEVICE_ORDER ON ORD_HOLDER.ID = ORD_DEVICE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_HOLDER.ID 
FROM ORD_HOLDER
WHERE 
[ORD_HOLDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_HOLDER.ID 
FROM ORD_HOLDER
 JOIN ORD_SALE_OF_GOODS_ORDER ON ORD_HOLDER.ID = ORD_SALE_OF_GOODS_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_HOLDER.ID 
FROM ORD_HOLDER
 JOIN ORD_VEHICLE_ORDER ON ORD_HOLDER.ID = ORD_VEHICLE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_ORDER_INSPECTION_TEXT_RSP_FOR_DELETE
SELECT DISTINCT INS_ORDER_INSPECTION_TEXT_RSP.ID 
FROM INS_ORDER_INSPECTION_TEXT_RSP
WHERE 
[INS_ORDER_INSPECTION_TEXT_RSP].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_ORDER_COMMON_BINARY_DATA_RSP_FOR_DELETE
SELECT DISTINCT INS_ORDER_COMMON_BINARY_DATA_RSP.ID 
FROM INS_ORDER_COMMON_BINARY_DATA_RSP
WHERE 
[INS_ORDER_COMMON_BINARY_DATA_RSP].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @VHL_VEHICLE_FOR_DELETE
SELECT DISTINCT VHL_VEHICLE.ID 
FROM VHL_VEHICLE
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @VHL_AXLE_FOR_DELETE
SELECT DISTINCT VHL_AXLE.ID 
FROM VHL_AXLE
 JOIN VHL_VERSION ON VHL_AXLE.VHL_VERSION_ID = VHL_VERSION.ID
 JOIN VHL_VEHICLE ON VHL_VERSION.ID = VHL_VEHICLE.VHL_VERSION_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_ORDER_FOR_DELETE
SELECT DISTINCT ORD_ORDER.ID 
FROM ORD_ORDER
WHERE 
[ORD_ORDER].[ID] IN ({0})
;

INSERT INTO @INS_PFP_NOTE_DEFECT_FOR_DELETE
SELECT DISTINCT INS_PFP_NOTE_DEFECT.ID 
FROM INS_PFP_NOTE_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_PFP_NOTE_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_PFP_DEFECT_FOR_DELETE
SELECT DISTINCT INS_PFP_DEFECT.ID 
FROM INS_PFP_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_PFP_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_OTHER_VALUE_FOR_DELETE
SELECT DISTINCT INS_OTHER_VALUE.ID 
FROM INS_OTHER_VALUE
 JOIN INS_INSPECTION_RESULT ON INS_OTHER_VALUE.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_MEASURED_VALUE_FOR_DELETE
SELECT DISTINCT INS_MEASURED_VALUE.ID 
FROM INS_MEASURED_VALUE
 JOIN INS_INSPECTION_RESULT ON INS_MEASURED_VALUE.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_INSPECTION_REPORT_FOR_DELETE
SELECT DISTINCT INS_INSPECTION_REPORT.ID 
FROM INS_INSPECTION_REPORT
 JOIN INS_INSPECTION_RESULT ON INS_INSPECTION_REPORT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_FOUND_OPTICAL_DEFECT_FOR_DELETE
SELECT DISTINCT INS_FOUND_OPTICAL_DEFECT.ID 
FROM INS_FOUND_OPTICAL_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_FOUND_OPTICAL_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_FOUND_DEFECT_FOR_DELETE
SELECT DISTINCT INS_FOUND_DEFECT.ID 
FROM INS_FOUND_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_FOUND_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_EXECUTABLE_INSPECTION_STEP_FOR_DELETE
SELECT DISTINCT INS_EXECUTABLE_INSPECTION_STEP.ID 
FROM INS_EXECUTABLE_INSPECTION_STEP
 JOIN ORD_POSITION_EXECUTABLE_INS_STEPS_RSP ON INS_EXECUTABLE_INSPECTION_STEP.ID = ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.INS_EXECUTABLE_INSPECTION_STEP_ID
 JOIN ORD_POSITION ON ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_EG_DOC_VEHICLE_DATA_FOR_DELETE
SELECT DISTINCT INS_EG_DOC_VEHICLE_DATA.ID 
FROM INS_EG_DOC_VEHICLE_DATA
 JOIN INS_INSPECTION_RESULT ON INS_EG_DOC_VEHICLE_DATA.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_ASA_PROBE_SIGNAL_DATA_FOR_DELETE
SELECT DISTINCT INS_ASA_PROBE_SIGNAL_DATA.ID 
FROM INS_ASA_PROBE_SIGNAL_DATA
 JOIN INS_INSPECTION_RESULT ON INS_ASA_PROBE_SIGNAL_DATA.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_ASA_ERROR_DATA_FOR_DELETE
SELECT DISTINCT INS_ASA_ERROR_DATA.ID 
FROM INS_ASA_ERROR_DATA
 JOIN INS_INSPECTION_RESULT ON INS_ASA_ERROR_DATA.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;


INSERT INTO @ORD_PERSON_FOR_DELETE
SELECT DISTINCT ORD_PERSON.ID 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_DEVICE_ORDER ON ORD_HOLDER.ID = ORD_DEVICE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_PERSON.ID 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
WHERE 
[ORD_HOLDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_PERSON.ID 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_SALE_OF_GOODS_ORDER ON ORD_HOLDER.ID = ORD_SALE_OF_GOODS_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_PERSON.ID 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_VEHICLE_ORDER ON ORD_HOLDER.ID = ORD_VEHICLE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_INSPECTION_RESULT_FOR_DELETE
SELECT DISTINCT INS_INSPECTION_RESULT.ID 
FROM INS_INSPECTION_RESULT
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;


INSERT INTO @ORD_DEVICE_FOR_DELETE
SELECT DISTINCT ORD_DEVICE.ID 
FROM ORD_DEVICE
 JOIN ORD_DEVICE_ORDER ON ORD_DEVICE.ID = ORD_DEVICE_ORDER.ORD_DEVICE_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @ORD_ADDRESS_FOR_DELETE
SELECT DISTINCT ORD_ADDRESS.ID 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_DEVICE_ORDER ON ORD_HOLDER.ID = ORD_DEVICE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.ID 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
WHERE 
[ORD_HOLDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.ID 
FROM ORD_ADDRESS
 JOIN ORD_ORDER ON ORD_ADDRESS.ID = ORD_ORDER.ORD_ADDRESS_ID
WHERE 
[ORD_ORDER].[ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.ID 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_SALE_OF_GOODS_ORDER ON ORD_HOLDER.ID = ORD_SALE_OF_GOODS_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.ID 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_VEHICLE_ORDER ON ORD_HOLDER.ID = ORD_VEHICLE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_INSPECTION_TEXT_FOR_DELETE
SELECT DISTINCT INS_INSPECTION_TEXT.ID 
FROM INS_INSPECTION_TEXT
 JOIN INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP ON INS_INSPECTION_TEXT.ID = INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.INS_INSPECTION_TEXT_ID
 JOIN ORD_POSITION ON INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT INS_INSPECTION_TEXT.ID 
FROM INS_INSPECTION_TEXT
 JOIN INS_ORDER_INSPECTION_TEXT_RSP ON INS_INSPECTION_TEXT.ID = INS_ORDER_INSPECTION_TEXT_RSP.INS_INSPECTION_TEXT_ID
WHERE 
[INS_ORDER_INSPECTION_TEXT_RSP].[ORD_ORDER_ID] IN ({0})
;

INSERT INTO @INS_INSPECTION_LABEL_FOR_DELETE
SELECT DISTINCT INS_INSPECTION_LABEL.ID 
FROM INS_INSPECTION_LABEL
 JOIN INS_INSPECTION_RESULT ON INS_INSPECTION_LABEL.ID = INS_INSPECTION_RESULT.INS_INSPECTION_LABEL_ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;


INSERT INTO @INS_COMMON_BINARY_DATA_FOR_DELETE
SELECT DISTINCT INS_COMMON_BINARY_DATA.ID 
FROM INS_COMMON_BINARY_DATA
 JOIN INS_ORDER_COMMON_BINARY_DATA_RSP ON INS_COMMON_BINARY_DATA.ID = INS_ORDER_COMMON_BINARY_DATA_RSP.INS_COMMON_BINARY_DATA_ID
WHERE 
[INS_ORDER_COMMON_BINARY_DATA_RSP].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT INS_COMMON_BINARY_DATA.ID 
FROM INS_COMMON_BINARY_DATA
 JOIN INS_POSITION_COMMON_BINARY_DATA_RSP ON INS_COMMON_BINARY_DATA.ID = INS_POSITION_COMMON_BINARY_DATA_RSP.INS_COMMON_BINARY_DATA_ID
 JOIN ORD_POSITION ON INS_POSITION_COMMON_BINARY_DATA_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;



INSERT INTO @VHL_MILE_AGE_FOR_DELETE
SELECT DISTINCT VHL_MILE_AGE.ID 
FROM VHL_MILE_AGE
 JOIN ORD_DEVICE ON VHL_MILE_AGE.ID = ORD_DEVICE.VHL_MILE_AGE_ID
 JOIN ORD_DEVICE_ORDER ON ORD_DEVICE.ID = ORD_DEVICE_ORDER.ORD_DEVICE_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT VHL_MILE_AGE.ID 
FROM VHL_MILE_AGE
 JOIN VHL_VEHICLE ON VHL_MILE_AGE.ID = VHL_VEHICLE.VHL_MILE_AGE_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;





INSERT INTO @ORD_ORDER_HISTORY_FOR_DELETE
SELECT DISTINCT ORD_ORDER_HISTORY.ID 
FROM ORD_ORDER_HISTORY
WHERE 
[ORD_ORDER_HISTORY].[ORD_ORDER_ID] IN ({0})
;


INSERT INTO @ORD_ACCOUNT_PARAMETER_FOR_DELETE
SELECT DISTINCT ORD_ACCOUNT_PARAMETER.ID 
FROM ORD_ACCOUNT_PARAMETER
 JOIN ORD_ORDER ON ORD_ACCOUNT_PARAMETER.ID = ORD_ORDER.ORD_ACCOUNT_PARAMETER_ID
WHERE 
[ORD_ORDER].[ID] IN ({0})
;

INSERT INTO @INS_INSPECTION_REPORT_BINARY_DATA_FOR_DELETE
SELECT DISTINCT INS_INSPECTION_REPORT_BINARY_DATA.ID 
FROM INS_INSPECTION_REPORT_BINARY_DATA
 JOIN INS_INSPECTION_REPORT ON INS_INSPECTION_REPORT_BINARY_DATA.ID = INS_INSPECTION_REPORT.INS_INSPECTION_REPORT_BINARY_DATA_ID
 JOIN INS_INSPECTION_RESULT ON INS_INSPECTION_REPORT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;


DELETE ORD_VEHICLE_ORDER FROM ORD_VEHICLE_ORDER tab JOIN @ORD_VEHICLE_ORDER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_SALE_OF_GOODS_ORDER FROM ORD_SALE_OF_GOODS_ORDER tab JOIN @ORD_SALE_OF_GOODS_ORDER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_PRODUCT_HISTORY FROM ORD_PRODUCT_HISTORY tab JOIN @ORD_PRODUCT_HISTORY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_POSITION_EXECUTABLE_INS_STEPS_RSP FROM ORD_POSITION_EXECUTABLE_INS_STEPS_RSP tab JOIN @ORD_POSITION_EXECUTABLE_INS_STEPS_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_POSITION_CASH_NUMBER FROM ORD_POSITION_CASH_NUMBER tab JOIN @ORD_POSITION_CASH_NUMBER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_DISCOUNT_INFO FROM ORD_DISCOUNT_INFO tab JOIN @ORD_DISCOUNT_INFO_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_DEVICE_ORDER FROM ORD_DEVICE_ORDER tab JOIN @ORD_DEVICE_ORDER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_POSITION_COMMON_BINARY_DATA_RSP FROM INS_POSITION_COMMON_BINARY_DATA_RSP tab JOIN @INS_POSITION_COMMON_BINARY_DATA_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP FROM INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP tab JOIN @INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_EMPLOYEE_PROPORTION FROM INS_EMPLOYEE_PROPORTION tab JOIN @INS_EMPLOYEE_PROPORTION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_SPECIAL_INFO_READ FROM VHL_SPECIAL_INFO_READ tab JOIN @VHL_SPECIAL_INFO_READ_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_POSITION FROM ORD_POSITION tab JOIN @ORD_POSITION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ORDER_ADDITIONAL_INFORMATION FROM ORD_ORDER_ADDITIONAL_INFORMATION tab JOIN @ORD_ORDER_ADDITIONAL_INFORMATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_HOLDER FROM ORD_HOLDER tab JOIN @ORD_HOLDER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_ORDER_INSPECTION_TEXT_RSP FROM INS_ORDER_INSPECTION_TEXT_RSP tab JOIN @INS_ORDER_INSPECTION_TEXT_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_ORDER_COMMON_BINARY_DATA_RSP FROM INS_ORDER_COMMON_BINARY_DATA_RSP tab JOIN @INS_ORDER_COMMON_BINARY_DATA_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_VEHICLE FROM VHL_VEHICLE tab JOIN @VHL_VEHICLE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE VHL_AXLE FROM VHL_AXLE tab JOIN @VHL_AXLE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ORDER FROM ORD_ORDER tab JOIN @ORD_ORDER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PFP_NOTE_DEFECT FROM INS_PFP_NOTE_DEFECT tab JOIN @INS_PFP_NOTE_DEFECT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_PFP_DEFECT FROM INS_PFP_DEFECT tab JOIN @INS_PFP_DEFECT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_OTHER_VALUE FROM INS_OTHER_VALUE tab JOIN @INS_OTHER_VALUE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_MEASURED_VALUE FROM INS_MEASURED_VALUE tab JOIN @INS_MEASURED_VALUE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_REPORT FROM INS_INSPECTION_REPORT tab JOIN @INS_INSPECTION_REPORT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_FOUND_OPTICAL_DEFECT FROM INS_FOUND_OPTICAL_DEFECT tab JOIN @INS_FOUND_OPTICAL_DEFECT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_FOUND_DEFECT FROM INS_FOUND_DEFECT tab JOIN @INS_FOUND_DEFECT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_EXECUTABLE_INSPECTION_STEP FROM INS_EXECUTABLE_INSPECTION_STEP tab JOIN @INS_EXECUTABLE_INSPECTION_STEP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_EG_DOC_VEHICLE_DATA FROM INS_EG_DOC_VEHICLE_DATA tab JOIN @INS_EG_DOC_VEHICLE_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_ASA_PROBE_SIGNAL_DATA FROM INS_ASA_PROBE_SIGNAL_DATA tab JOIN @INS_ASA_PROBE_SIGNAL_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_ASA_ERROR_DATA FROM INS_ASA_ERROR_DATA tab JOIN @INS_ASA_ERROR_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID

DELETE ORD_PERSON FROM ORD_PERSON tab JOIN @ORD_PERSON_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_RESULT FROM INS_INSPECTION_RESULT tab JOIN @INS_INSPECTION_RESULT_FOR_DELETE idlist ON tab.ID = idlist.ID

DELETE ORD_DEVICE FROM ORD_DEVICE tab JOIN @ORD_DEVICE_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE ORD_ADDRESS FROM ORD_ADDRESS tab JOIN @ORD_ADDRESS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_TEXT FROM INS_INSPECTION_TEXT tab JOIN @INS_INSPECTION_TEXT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_LABEL FROM INS_INSPECTION_LABEL tab JOIN @INS_INSPECTION_LABEL_FOR_DELETE idlist ON tab.ID = idlist.ID

DELETE INS_COMMON_BINARY_DATA FROM INS_COMMON_BINARY_DATA tab JOIN @INS_COMMON_BINARY_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID


DELETE VHL_MILE_AGE FROM VHL_MILE_AGE tab JOIN @VHL_MILE_AGE_FOR_DELETE idlist ON tab.ID = idlist.ID




DELETE ORD_ORDER_HISTORY FROM ORD_ORDER_HISTORY tab JOIN @ORD_ORDER_HISTORY_FOR_DELETE idlist ON tab.ID = idlist.ID

DELETE ORD_ACCOUNT_PARAMETER FROM ORD_ACCOUNT_PARAMETER tab JOIN @ORD_ACCOUNT_PARAMETER_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE INS_INSPECTION_REPORT_BINARY_DATA FROM INS_INSPECTION_REPORT_BINARY_DATA tab JOIN @INS_INSPECTION_REPORT_BINARY_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID
