SELECT DISTINCT INS_INSPECTION_REPORT_BINARY_DATA.* 
FROM INS_INSPECTION_REPORT_BINARY_DATA
 JOIN INS_INSPECTION_REPORT ON INS_INSPECTION_REPORT_BINARY_DATA.ID = INS_INSPECTION_REPORT.INS_INSPECTION_REPORT_BINARY_DATA_ID
 JOIN INS_INSPECTION_RESULT ON INS_INSPECTION_REPORT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_ACCOUNT_PARAMETER.* 
FROM ORD_ACCOUNT_PARAMETER
 JOIN ORD_ORDER ON ORD_ACCOUNT_PARAMETER.ID = ORD_ORDER.ORD_ACCOUNT_PARAMETER_ID
WHERE 
[ORD_ORDER].[ID] IN ({0})
;

SELECT DISTINCT ORD_ORDER_FOLDER.* 
FROM ORD_ORDER_FOLDER
 JOIN ORD_ORDER ON ORD_ORDER_FOLDER.ID = ORD_ORDER.ORD_ORDER_FOLDER_ID
WHERE 
[ORD_ORDER].[ID] IN ({0})
;

SELECT DISTINCT ORD_ORDER_HISTORY.* 
FROM ORD_ORDER_HISTORY
WHERE 
[ORD_ORDER_HISTORY].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_BODY.* 
FROM VHL_BODY
 JOIN VHL_VEHICLE ON VHL_BODY.ID = VHL_VEHICLE.VHL_BODY_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_CLASS.* 
FROM VHL_CLASS
 JOIN VHL_VEHICLE ON VHL_CLASS.ID = VHL_VEHICLE.VHL_CLASS_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_EMISSION_CLASS.* 
FROM VHL_EMISSION_CLASS
 JOIN VHL_VEHICLE ON VHL_EMISSION_CLASS.ID = VHL_VEHICLE.VHL_EMISSION_CLASS_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_FUEL_TYPE.* 
FROM VHL_FUEL_TYPE
 JOIN VHL_VEHICLE ON VHL_FUEL_TYPE.ID = VHL_VEHICLE.VHL_FUEL_TYPE_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_MILE_AGE.* 
FROM VHL_MILE_AGE
 JOIN ORD_DEVICE ON VHL_MILE_AGE.ID = ORD_DEVICE.VHL_MILE_AGE_ID
 JOIN ORD_DEVICE_ORDER ON ORD_DEVICE.ID = ORD_DEVICE_ORDER.ORD_DEVICE_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT VHL_MILE_AGE.* 
FROM VHL_MILE_AGE
 JOIN VHL_VEHICLE ON VHL_MILE_AGE.ID = VHL_VEHICLE.VHL_MILE_AGE_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_PRODUCER.* 
FROM VHL_PRODUCER
 JOIN VHL_PRODUCER_TYPE ON VHL_PRODUCER.ID = VHL_PRODUCER_TYPE.VHL_PRODUCER_ID
 JOIN VHL_VERSION ON VHL_PRODUCER_TYPE.ID = VHL_VERSION.VHL_PRODUCER_TYPE_ID
 JOIN VHL_VEHICLE ON VHL_VERSION.ID = VHL_VEHICLE.VHL_VERSION_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_TYPE.* 
FROM VHL_TYPE
 JOIN VHL_PRODUCER_TYPE ON VHL_TYPE.ID = VHL_PRODUCER_TYPE.VHL_TYPE_ID
 JOIN VHL_VERSION ON VHL_PRODUCER_TYPE.ID = VHL_VERSION.VHL_PRODUCER_TYPE_ID
 JOIN VHL_VEHICLE ON VHL_VERSION.ID = VHL_VEHICLE.VHL_VERSION_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_COMMON_BINARY_DATA.* 
FROM INS_COMMON_BINARY_DATA
 JOIN INS_ORDER_COMMON_BINARY_DATA_RSP ON INS_COMMON_BINARY_DATA.ID = INS_ORDER_COMMON_BINARY_DATA_RSP.INS_COMMON_BINARY_DATA_ID
WHERE 
[INS_ORDER_COMMON_BINARY_DATA_RSP].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT INS_COMMON_BINARY_DATA.* 
FROM INS_COMMON_BINARY_DATA
 JOIN INS_POSITION_COMMON_BINARY_DATA_RSP ON INS_COMMON_BINARY_DATA.ID = INS_POSITION_COMMON_BINARY_DATA_RSP.INS_COMMON_BINARY_DATA_ID
 JOIN ORD_POSITION ON INS_POSITION_COMMON_BINARY_DATA_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_DEFECT.* 
FROM INS_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_DEFECT.ID = INS_INSPECTION_RESULT.FINAL_DEFECT_ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT INS_DEFECT.* 
FROM INS_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_DEFECT.ID = INS_INSPECTION_RESULT.INTERMEDIATE_DEFECT_ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT INS_DEFECT.* 
FROM INS_DEFECT
 JOIN INS_FOUND_DEFECT ON INS_DEFECT.ID = INS_FOUND_DEFECT.INS_DEFECT_ID
 JOIN INS_INSPECTION_RESULT ON INS_FOUND_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_INSPECTION_LABEL.* 
FROM INS_INSPECTION_LABEL
 JOIN INS_INSPECTION_RESULT ON INS_INSPECTION_LABEL.ID = INS_INSPECTION_RESULT.INS_INSPECTION_LABEL_ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_INSPECTION_TEXT.* 
FROM INS_INSPECTION_TEXT
 JOIN INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP ON INS_INSPECTION_TEXT.ID = INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.INS_INSPECTION_TEXT_ID
 JOIN ORD_POSITION ON INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT INS_INSPECTION_TEXT.* 
FROM INS_INSPECTION_TEXT
 JOIN INS_ORDER_INSPECTION_TEXT_RSP ON INS_INSPECTION_TEXT.ID = INS_ORDER_INSPECTION_TEXT_RSP.INS_INSPECTION_TEXT_ID
WHERE 
[INS_ORDER_INSPECTION_TEXT_RSP].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_ADDRESS.* 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_DEVICE_ORDER ON ORD_HOLDER.ID = ORD_DEVICE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.* 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
WHERE 
[ORD_HOLDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.* 
FROM ORD_ADDRESS
 JOIN ORD_ORDER ON ORD_ADDRESS.ID = ORD_ORDER.ORD_ADDRESS_ID
WHERE 
[ORD_ORDER].[ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.* 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_SALE_OF_GOODS_ORDER ON ORD_HOLDER.ID = ORD_SALE_OF_GOODS_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_ADDRESS.* 
FROM ORD_ADDRESS
 JOIN ORD_PERSON ON ORD_ADDRESS.ID = ORD_PERSON.ORD_ADDRESS_ID
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_VEHICLE_ORDER ON ORD_HOLDER.ID = ORD_VEHICLE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_DEVICE.* 
FROM ORD_DEVICE
 JOIN ORD_DEVICE_ORDER ON ORD_DEVICE.ID = ORD_DEVICE_ORDER.ORD_DEVICE_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_PRODUCER_TYPE.* 
FROM VHL_PRODUCER_TYPE
 JOIN VHL_VERSION ON VHL_PRODUCER_TYPE.ID = VHL_VERSION.VHL_PRODUCER_TYPE_ID
 JOIN VHL_VEHICLE ON VHL_VERSION.ID = VHL_VEHICLE.VHL_VERSION_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_INSPECTION_RESULT.* 
FROM INS_INSPECTION_RESULT
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_PERSON.* 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_DEVICE_ORDER ON ORD_HOLDER.ID = ORD_DEVICE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_PERSON.* 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
WHERE 
[ORD_HOLDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_PERSON.* 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_SALE_OF_GOODS_ORDER ON ORD_HOLDER.ID = ORD_SALE_OF_GOODS_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_PERSON.* 
FROM ORD_PERSON
 JOIN ORD_HOLDER ON ORD_PERSON.ID = ORD_HOLDER.ORD_PERSON_ID
 JOIN ORD_VEHICLE_ORDER ON ORD_HOLDER.ID = ORD_VEHICLE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_VERSION.* 
FROM VHL_VERSION
 JOIN VHL_VEHICLE ON VHL_VERSION.ID = VHL_VEHICLE.VHL_VERSION_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_ASA_ERROR_DATA.* 
FROM INS_ASA_ERROR_DATA
 JOIN INS_INSPECTION_RESULT ON INS_ASA_ERROR_DATA.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_ASA_PROBE_SIGNAL_DATA.* 
FROM INS_ASA_PROBE_SIGNAL_DATA
 JOIN INS_INSPECTION_RESULT ON INS_ASA_PROBE_SIGNAL_DATA.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_EG_DOC_VEHICLE_DATA.* 
FROM INS_EG_DOC_VEHICLE_DATA
 JOIN INS_INSPECTION_RESULT ON INS_EG_DOC_VEHICLE_DATA.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_EXECUTABLE_INSPECTION_STEP.* 
FROM INS_EXECUTABLE_INSPECTION_STEP
 JOIN ORD_POSITION_EXECUTABLE_INS_STEPS_RSP ON INS_EXECUTABLE_INSPECTION_STEP.ID = ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.INS_EXECUTABLE_INSPECTION_STEP_ID
 JOIN ORD_POSITION ON ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_FOUND_DEFECT.* 
FROM INS_FOUND_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_FOUND_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_FOUND_OPTICAL_DEFECT.* 
FROM INS_FOUND_OPTICAL_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_FOUND_OPTICAL_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_INSPECTION_REPORT.* 
FROM INS_INSPECTION_REPORT
 JOIN INS_INSPECTION_RESULT ON INS_INSPECTION_REPORT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_MEASURED_VALUE.* 
FROM INS_MEASURED_VALUE
 JOIN INS_INSPECTION_RESULT ON INS_MEASURED_VALUE.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_OTHER_VALUE.* 
FROM INS_OTHER_VALUE
 JOIN INS_INSPECTION_RESULT ON INS_OTHER_VALUE.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_PFP_DEFECT.* 
FROM INS_PFP_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_PFP_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_PFP_NOTE_DEFECT.* 
FROM INS_PFP_NOTE_DEFECT
 JOIN INS_INSPECTION_RESULT ON INS_PFP_NOTE_DEFECT.INS_INSPECTION_RESULT_ID = INS_INSPECTION_RESULT.ID
 JOIN ORD_POSITION ON INS_INSPECTION_RESULT.ID = ORD_POSITION.INS_INSPECTION_RESULT_ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_ORDER.* 
FROM ORD_ORDER
WHERE 
[ORD_ORDER].[ID] IN ({0})
;

SELECT DISTINCT VHL_AXLE.* 
FROM VHL_AXLE
 JOIN VHL_VERSION ON VHL_AXLE.VHL_VERSION_ID = VHL_VERSION.ID
 JOIN VHL_VEHICLE ON VHL_VERSION.ID = VHL_VEHICLE.VHL_VERSION_ID
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_VEHICLE.* 
FROM VHL_VEHICLE
 JOIN ORD_VEHICLE_ORDER ON VHL_VEHICLE.ID = ORD_VEHICLE_ORDER.VHL_VEHICLE_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_ORDER_COMMON_BINARY_DATA_RSP.* 
FROM INS_ORDER_COMMON_BINARY_DATA_RSP
WHERE 
[INS_ORDER_COMMON_BINARY_DATA_RSP].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_ORDER_INSPECTION_TEXT_RSP.* 
FROM INS_ORDER_INSPECTION_TEXT_RSP
WHERE 
[INS_ORDER_INSPECTION_TEXT_RSP].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_HOLDER.* 
FROM ORD_HOLDER
 JOIN ORD_DEVICE_ORDER ON ORD_HOLDER.ID = ORD_DEVICE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_HOLDER.* 
FROM ORD_HOLDER
WHERE 
[ORD_HOLDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_HOLDER.* 
FROM ORD_HOLDER
 JOIN ORD_SALE_OF_GOODS_ORDER ON ORD_HOLDER.ID = ORD_SALE_OF_GOODS_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})

UNION

SELECT DISTINCT ORD_HOLDER.* 
FROM ORD_HOLDER
 JOIN ORD_VEHICLE_ORDER ON ORD_HOLDER.ID = ORD_VEHICLE_ORDER.ORD_HOLDER_ID
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_ORDER_ADDITIONAL_INFORMATION.* 
FROM ORD_ORDER_ADDITIONAL_INFORMATION
WHERE 
[ORD_ORDER_ADDITIONAL_INFORMATION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_POSITION.* 
FROM ORD_POSITION
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT VHL_SPECIAL_INFO_READ.* 
FROM VHL_SPECIAL_INFO_READ
WHERE 
[VHL_SPECIAL_INFO_READ].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_EMPLOYEE_PROPORTION.* 
FROM INS_EMPLOYEE_PROPORTION
 JOIN ORD_POSITION ON INS_EMPLOYEE_PROPORTION.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.* 
FROM INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP
 JOIN ORD_POSITION ON INS_INSPECTION_PRODUCT_INSPECTION_TEXT_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT INS_POSITION_COMMON_BINARY_DATA_RSP.* 
FROM INS_POSITION_COMMON_BINARY_DATA_RSP
 JOIN ORD_POSITION ON INS_POSITION_COMMON_BINARY_DATA_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_DEVICE_ORDER.* 
FROM ORD_DEVICE_ORDER
WHERE 
[ORD_DEVICE_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_DISCOUNT_INFO.* 
FROM ORD_DISCOUNT_INFO
 JOIN ORD_POSITION ON ORD_DISCOUNT_INFO.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_POSITION_CASH_NUMBER.* 
FROM ORD_POSITION_CASH_NUMBER
 JOIN ORD_POSITION ON ORD_POSITION_CASH_NUMBER.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.* 
FROM ORD_POSITION_EXECUTABLE_INS_STEPS_RSP
 JOIN ORD_POSITION ON ORD_POSITION_EXECUTABLE_INS_STEPS_RSP.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_PRODUCT_HISTORY.* 
FROM ORD_PRODUCT_HISTORY
 JOIN ORD_POSITION ON ORD_PRODUCT_HISTORY.ORD_POSITION_ID = ORD_POSITION.ID
WHERE 
[ORD_POSITION].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_SALE_OF_GOODS_ORDER.* 
FROM ORD_SALE_OF_GOODS_ORDER
WHERE 
[ORD_SALE_OF_GOODS_ORDER].[ORD_ORDER_ID] IN ({0})
;

SELECT DISTINCT ORD_VEHICLE_ORDER.* 
FROM ORD_VEHICLE_ORDER
WHERE 
[ORD_VEHICLE_ORDER].[ORD_ORDER_ID] IN ({0})
;
