DECLARE @SYS_LOG_ENTRY_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @SYS_PROTOCOL_FOR_DELETE TABLE(ID uniqueidentifier)

INSERT INTO @SYS_LOG_ENTRY_FOR_DELETE
SELECT  SYS_LOG_ENTRY.ID 
FROM SYS_LOG_ENTRY
WHERE 
[SYS_LOG_ENTRY].[ID] IN ({0})
;

INSERT INTO @SYS_PROTOCOL_FOR_DELETE
SELECT  SYS_PROTOCOL.ID 
FROM SYS_PROTOCOL
WHERE 
[SYS_PROTOCOL].[ID] IN ({0})
;


DELETE SYS_LOG_ENTRY FROM SYS_LOG_ENTRY tab JOIN @SYS_LOG_ENTRY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE SYS_PROTOCOL FROM SYS_PROTOCOL tab JOIN @SYS_PROTOCOL_FOR_DELETE idlist ON tab.ID = idlist.ID
