DECLARE @KSS_OPERATION_ORD_POSITION_RSP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_OPERATION_DOCUMENT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_OPERATION_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_CASH_DOCUMENT_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_CASH_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_INVOICE_COPY_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_TRANSF_CASH_COPY_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_POS_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @KSS_CHECK_FOR_DELETE TABLE(ID uniqueidentifier)

INSERT INTO @KSS_OPERATION_ORD_POSITION_RSP_FOR_DELETE
SELECT DISTINCT KSS_OPERATION_ORD_POSITION_RSP.ID 
FROM KSS_OPERATION_ORD_POSITION_RSP
 JOIN KSS_OPERATION ON KSS_OPERATION_ORD_POSITION_RSP.KSS_OPERATION_ID = KSS_OPERATION.ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_OPERATION_DOCUMENT_FOR_DELETE
SELECT DISTINCT KSS_OPERATION_DOCUMENT.ID 
FROM KSS_OPERATION_DOCUMENT
 JOIN KSS_OPERATION ON KSS_OPERATION_DOCUMENT.KSS_OPERATION_ID = KSS_OPERATION.ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_OPERATION_FOR_DELETE
SELECT DISTINCT KSS_OPERATION.ID 
FROM KSS_OPERATION
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_CASH_DOCUMENT_FOR_DELETE
SELECT DISTINCT KSS_CASH_DOCUMENT.ID 
FROM KSS_CASH_DOCUMENT
WHERE 
[KSS_CASH_DOCUMENT].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_CASH_FOR_DELETE
SELECT DISTINCT KSS_CASH.ID 
FROM KSS_CASH
WHERE 
[KSS_CASH].[ID] IN ({0})
;

INSERT INTO @KSS_INVOICE_COPY_FOR_DELETE
SELECT DISTINCT KSS_INVOICE_COPY.ID 
FROM KSS_INVOICE_COPY
 JOIN KSS_OPERATION ON KSS_INVOICE_COPY.ID = KSS_OPERATION.KSS_INVOICE_COPY_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_TRANSF_CASH_COPY_FOR_DELETE
SELECT DISTINCT KSS_TRANSF_CASH_COPY.ID 
FROM KSS_TRANSF_CASH_COPY
 JOIN KSS_OPERATION ON KSS_TRANSF_CASH_COPY.ID = KSS_OPERATION.KSS_TRANSF_CASH_COPY_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_POS_FOR_DELETE
SELECT DISTINCT KSS_POS.ID 
FROM KSS_POS
 JOIN KSS_OPERATION ON KSS_POS.ID = KSS_OPERATION.KSS_POS_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;

INSERT INTO @KSS_CHECK_FOR_DELETE
SELECT DISTINCT KSS_CHECK.ID 
FROM KSS_CHECK
 JOIN KSS_OPERATION ON KSS_CHECK.ID = KSS_OPERATION.KSS_CHECK_ID
WHERE 
[KSS_OPERATION].[KSS_CASH_ID] IN ({0})
;


DELETE KSS_OPERATION_ORD_POSITION_RSP FROM KSS_OPERATION_ORD_POSITION_RSP tab JOIN @KSS_OPERATION_ORD_POSITION_RSP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_OPERATION_DOCUMENT FROM KSS_OPERATION_DOCUMENT tab JOIN @KSS_OPERATION_DOCUMENT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_OPERATION FROM KSS_OPERATION tab JOIN @KSS_OPERATION_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_CASH_DOCUMENT FROM KSS_CASH_DOCUMENT tab JOIN @KSS_CASH_DOCUMENT_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_CASH FROM KSS_CASH tab JOIN @KSS_CASH_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_INVOICE_COPY FROM KSS_INVOICE_COPY tab JOIN @KSS_INVOICE_COPY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_TRANSF_CASH_COPY FROM KSS_TRANSF_CASH_COPY tab JOIN @KSS_TRANSF_CASH_COPY_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_POS FROM KSS_POS tab JOIN @KSS_POS_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE KSS_CHECK FROM KSS_CHECK tab JOIN @KSS_CHECK_FOR_DELETE idlist ON tab.ID = idlist.ID
