DECLARE @EXP_WORKING_SPAN_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @EXP_TRIP_FOR_DELETE TABLE(ID uniqueidentifier)
DECLARE @EXP_WORKING_DAY_FOR_DELETE TABLE(ID uniqueidentifier)

INSERT INTO @EXP_WORKING_SPAN_FOR_DELETE
SELECT DISTINCT EXP_WORKING_SPAN.ID 
FROM EXP_WORKING_SPAN
WHERE 
[EXP_WORKING_SPAN].[EXP_WORKING_DAY_ID] IN ({0})
;

INSERT INTO @EXP_TRIP_FOR_DELETE
SELECT DISTINCT EXP_TRIP.ID 
FROM EXP_TRIP
WHERE 
[EXP_TRIP].[EXP_WORKING_DAY_ID] IN ({0})
;

INSERT INTO @EXP_WORKING_DAY_FOR_DELETE
SELECT DISTINCT EXP_WORKING_DAY.ID 
FROM EXP_WORKING_DAY
WHERE 
[EXP_WORKING_DAY].[ID] IN ({0})
;


DELETE EXP_WORKING_SPAN FROM EXP_WORKING_SPAN tab JOIN @EXP_WORKING_SPAN_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EXP_TRIP FROM EXP_TRIP tab JOIN @EXP_TRIP_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EXP_WORKING_DAY FROM EXP_WORKING_DAY tab JOIN @EXP_WORKING_DAY_FOR_DELETE idlist ON tab.ID = idlist.ID
