DECLARE @SYS_PASSWORD_FOR_DELETE TABLE(ID int)
DECLARE @EMP_LOGIN_DATA_FOR_DELETE TABLE(ID int)

INSERT INTO @SYS_PASSWORD_FOR_DELETE
SELECT  SYS_PASSWORD.ID 
FROM SYS_PASSWORD
WHERE 
[SYS_PASSWORD].[ROW_VERSION] > {0}
;

INSERT INTO @EMP_LOGIN_DATA_FOR_DELETE
SELECT  EMP_LOGIN_DATA.ID 
FROM EMP_LOGIN_DATA
WHERE 
[EMP_LOGIN_DATA].[ROW_VERSION] > {0}
;


DELETE SYS_PASSWORD FROM SYS_PASSWORD tab JOIN @SYS_PASSWORD_FOR_DELETE idlist ON tab.ID = idlist.ID
DELETE EMP_LOGIN_DATA FROM EMP_LOGIN_DATA tab JOIN @EMP_LOGIN_DATA_FOR_DELETE idlist ON tab.ID = idlist.ID
